/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.records;


import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.TableRecordImpl;

import unid.jooqMono.model.tables._AuditLogStudentProfileQuestionnaireAnswerMapTable;
import unid.jooqMono.model.tables.pojos._AuditLogStudentProfileQuestionnaireAnswerMapPojo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class _AuditLogStudentProfileQuestionnaireAnswerMapRecord extends TableRecordImpl<_AuditLogStudentProfileQuestionnaireAnswerMapRecord> implements Record15<Long, OffsetDateTime, String, String, String, UUID, UUID, UUID, UUID, Integer, String, OffsetDateTime, String, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.audit_seq</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setAuditSeq(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.audit_seq</code>.
     */
    @Nonnull
    public Long getAuditSeq() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.audit_createdon</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setAuditCreatedon(@Nonnull OffsetDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.audit_createdon</code>.
     */
    @Nonnull
    public OffsetDateTime getAuditCreatedon() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.audit_createdby</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setAuditCreatedby(@Nonnull String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.audit_createdby</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditCreatedby() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.audit_operation</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setAuditOperation(@Nonnull String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.audit_operation</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditOperation() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.audit_type</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setAuditType(@Nonnull String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.audit_type</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditType() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.id</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setId(@Nonnull UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getId() {
        return (UUID) get(5);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.student_profile_questionnaire_map_id</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setStudentProfileQuestionnaireMapId(@Nonnull UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.student_profile_questionnaire_map_id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getStudentProfileQuestionnaireMapId() {
        return (UUID) get(6);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.questionnaire_question_id</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setQuestionnaireQuestionId(@Nonnull UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.questionnaire_question_id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getQuestionnaireQuestionId() {
        return (UUID) get(7);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.questionnaire_answer_id</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setQuestionnaireAnswerId(@Nonnull UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.questionnaire_answer_id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getQuestionnaireAnswerId() {
        return (UUID) get(8);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.questionnaire_answer_order</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setQuestionnaireAnswerOrder(@Nonnull Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.questionnaire_answer_order</code>.
     */
    @NotNull
    @Nonnull
    public Integer getQuestionnaireAnswerOrder() {
        return (Integer) get(9);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.questionnaire_answer_any_input</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setQuestionnaireAnswerAnyInput(@Nullable String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.questionnaire_answer_any_input</code>.
     */
    @Nullable
    public String getQuestionnaireAnswerAnyInput() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.created_on</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setCreatedOn(@Nullable OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.created_on</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.created_by</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setCreatedBy(@Nullable String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.created_by</code>.
     */
    @Nullable
    public String getCreatedBy() {
        return (String) get(12);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.updated_on</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setUpdatedOn(@Nullable OffsetDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.updated_on</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedOn() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.updated_by</code>.
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord setUpdatedBy(@Nullable String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_questionnaire_answer_map.updated_by</code>.
     */
    @Nullable
    public String getUpdatedBy() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row15<Long, OffsetDateTime, String, String, String, UUID, UUID, UUID, UUID, Integer, String, OffsetDateTime, String, OffsetDateTime, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row15<Long, OffsetDateTime, String, String, String, UUID, UUID, UUID, UUID, Integer, String, OffsetDateTime, String, OffsetDateTime, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Long> field1() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.AUDIT_SEQ;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field2() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.AUDIT_CREATEDON;
    }

    @Override
    @Nonnull
    public Field<String> field3() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.AUDIT_CREATEDBY;
    }

    @Override
    @Nonnull
    public Field<String> field4() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.AUDIT_OPERATION;
    }

    @Override
    @Nonnull
    public Field<String> field5() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.AUDIT_TYPE;
    }

    @Override
    @Nonnull
    public Field<UUID> field6() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.ID;
    }

    @Override
    @Nonnull
    public Field<UUID> field7() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.STUDENT_PROFILE_QUESTIONNAIRE_MAP_ID;
    }

    @Override
    @Nonnull
    public Field<UUID> field8() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.QUESTIONNAIRE_QUESTION_ID;
    }

    @Override
    @Nonnull
    public Field<UUID> field9() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.QUESTIONNAIRE_ANSWER_ID;
    }

    @Override
    @Nonnull
    public Field<Integer> field10() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.QUESTIONNAIRE_ANSWER_ORDER;
    }

    @Override
    @Nonnull
    public Field<String> field11() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.QUESTIONNAIRE_ANSWER_ANY_INPUT;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field12() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.CREATED_ON;
    }

    @Override
    @Nonnull
    public Field<String> field13() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.CREATED_BY;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field14() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.UPDATED_ON;
    }

    @Override
    @Nonnull
    public Field<String> field15() {
        return _AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP.UPDATED_BY;
    }

    @Override
    @Nonnull
    public Long component1() {
        return getAuditSeq();
    }

    @Override
    @Nonnull
    public OffsetDateTime component2() {
        return getAuditCreatedon();
    }

    @Override
    @Nonnull
    public String component3() {
        return getAuditCreatedby();
    }

    @Override
    @Nonnull
    public String component4() {
        return getAuditOperation();
    }

    @Override
    @Nonnull
    public String component5() {
        return getAuditType();
    }

    @Override
    @Nonnull
    public UUID component6() {
        return getId();
    }

    @Override
    @Nonnull
    public UUID component7() {
        return getStudentProfileQuestionnaireMapId();
    }

    @Override
    @Nonnull
    public UUID component8() {
        return getQuestionnaireQuestionId();
    }

    @Override
    @Nonnull
    public UUID component9() {
        return getQuestionnaireAnswerId();
    }

    @Override
    @Nonnull
    public Integer component10() {
        return getQuestionnaireAnswerOrder();
    }

    @Override
    @Nullable
    public String component11() {
        return getQuestionnaireAnswerAnyInput();
    }

    @Override
    @Nullable
    public OffsetDateTime component12() {
        return getCreatedOn();
    }

    @Override
    @Nullable
    public String component13() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public OffsetDateTime component14() {
        return getUpdatedOn();
    }

    @Override
    @Nullable
    public String component15() {
        return getUpdatedBy();
    }

    @Override
    @Nonnull
    public Long value1() {
        return getAuditSeq();
    }

    @Override
    @Nonnull
    public OffsetDateTime value2() {
        return getAuditCreatedon();
    }

    @Override
    @Nonnull
    public String value3() {
        return getAuditCreatedby();
    }

    @Override
    @Nonnull
    public String value4() {
        return getAuditOperation();
    }

    @Override
    @Nonnull
    public String value5() {
        return getAuditType();
    }

    @Override
    @Nonnull
    public UUID value6() {
        return getId();
    }

    @Override
    @Nonnull
    public UUID value7() {
        return getStudentProfileQuestionnaireMapId();
    }

    @Override
    @Nonnull
    public UUID value8() {
        return getQuestionnaireQuestionId();
    }

    @Override
    @Nonnull
    public UUID value9() {
        return getQuestionnaireAnswerId();
    }

    @Override
    @Nonnull
    public Integer value10() {
        return getQuestionnaireAnswerOrder();
    }

    @Override
    @Nullable
    public String value11() {
        return getQuestionnaireAnswerAnyInput();
    }

    @Override
    @Nullable
    public OffsetDateTime value12() {
        return getCreatedOn();
    }

    @Override
    @Nullable
    public String value13() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public OffsetDateTime value14() {
        return getUpdatedOn();
    }

    @Override
    @Nullable
    public String value15() {
        return getUpdatedBy();
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value1(@Nonnull Long value) {
        setAuditSeq(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value2(@Nonnull OffsetDateTime value) {
        setAuditCreatedon(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value3(@Nonnull String value) {
        setAuditCreatedby(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value4(@Nonnull String value) {
        setAuditOperation(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value5(@Nonnull String value) {
        setAuditType(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value6(@Nonnull UUID value) {
        setId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value7(@Nonnull UUID value) {
        setStudentProfileQuestionnaireMapId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value8(@Nonnull UUID value) {
        setQuestionnaireQuestionId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value9(@Nonnull UUID value) {
        setQuestionnaireAnswerId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value10(@Nonnull Integer value) {
        setQuestionnaireAnswerOrder(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value11(@Nullable String value) {
        setQuestionnaireAnswerAnyInput(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value12(@Nullable OffsetDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value13(@Nullable String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value14(@Nullable OffsetDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord value15(@Nullable String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord values(@Nonnull Long value1, @Nonnull OffsetDateTime value2, @Nonnull String value3, @Nonnull String value4, @Nonnull String value5, @Nonnull UUID value6, @Nonnull UUID value7, @Nonnull UUID value8, @Nonnull UUID value9, @Nonnull Integer value10, @Nullable String value11, @Nullable OffsetDateTime value12, @Nullable String value13, @Nullable OffsetDateTime value14, @Nullable String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _AuditLogStudentProfileQuestionnaireAnswerMapRecord
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord() {
        super(_AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP);
    }

    /**
     * Create a detached, initialised
     * _AuditLogStudentProfileQuestionnaireAnswerMapRecord
     */
    @ConstructorProperties({ "auditSeq", "auditCreatedon", "auditCreatedby", "auditOperation", "auditType", "id", "studentProfileQuestionnaireMapId", "questionnaireQuestionId", "questionnaireAnswerId", "questionnaireAnswerOrder", "questionnaireAnswerAnyInput", "createdOn", "createdBy", "updatedOn", "updatedBy" })
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord(@Nonnull Long auditSeq, @Nonnull OffsetDateTime auditCreatedon, @Nonnull String auditCreatedby, @Nonnull String auditOperation, @Nonnull String auditType, @Nonnull UUID id, @Nonnull UUID studentProfileQuestionnaireMapId, @Nonnull UUID questionnaireQuestionId, @Nonnull UUID questionnaireAnswerId, @Nonnull Integer questionnaireAnswerOrder, @Nullable String questionnaireAnswerAnyInput, @Nullable OffsetDateTime createdOn, @Nullable String createdBy, @Nullable OffsetDateTime updatedOn, @Nullable String updatedBy) {
        super(_AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP);

        setAuditSeq(auditSeq);
        setAuditCreatedon(auditCreatedon);
        setAuditCreatedby(auditCreatedby);
        setAuditOperation(auditOperation);
        setAuditType(auditType);
        setId(id);
        setStudentProfileQuestionnaireMapId(studentProfileQuestionnaireMapId);
        setQuestionnaireQuestionId(questionnaireQuestionId);
        setQuestionnaireAnswerId(questionnaireAnswerId);
        setQuestionnaireAnswerOrder(questionnaireAnswerOrder);
        setQuestionnaireAnswerAnyInput(questionnaireAnswerAnyInput);
        setCreatedOn(createdOn);
        setCreatedBy(createdBy);
        setUpdatedOn(updatedOn);
        setUpdatedBy(updatedBy);
    }

    /**
     * Create a detached, initialised
     * _AuditLogStudentProfileQuestionnaireAnswerMapRecord
     */
    public _AuditLogStudentProfileQuestionnaireAnswerMapRecord(_AuditLogStudentProfileQuestionnaireAnswerMapPojo value) {
        super(_AuditLogStudentProfileQuestionnaireAnswerMapTable._AUDIT_LOG_STUDENT_PROFILE_QUESTIONNAIRE_ANSWER_MAP);

        if (value != null) {
            setAuditSeq(value.getAuditSeq());
            setAuditCreatedon(value.getAuditCreatedon());
            setAuditCreatedby(value.getAuditCreatedby());
            setAuditOperation(value.getAuditOperation());
            setAuditType(value.getAuditType());
            setId(value.getId());
            setStudentProfileQuestionnaireMapId(value.getStudentProfileQuestionnaireMapId());
            setQuestionnaireQuestionId(value.getQuestionnaireQuestionId());
            setQuestionnaireAnswerId(value.getQuestionnaireAnswerId());
            setQuestionnaireAnswerOrder(value.getQuestionnaireAnswerOrder());
            setQuestionnaireAnswerAnyInput(value.getQuestionnaireAnswerAnyInput());
            setCreatedOn(value.getCreatedOn());
            setCreatedBy(value.getCreatedBy());
            setUpdatedOn(value.getUpdatedOn());
            setUpdatedBy(value.getUpdatedBy());
        }
    }
}
