/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.records;


import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;

import unid.jooqMono.model.tables._AuditLogStudentQuestionnaireTable;
import unid.jooqMono.model.tables.pojos._AuditLogStudentQuestionnairePojo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class _AuditLogStudentQuestionnaireRecord extends TableRecordImpl<_AuditLogStudentQuestionnaireRecord> implements Record16<Long, OffsetDateTime, String, String, String, UUID, OffsetDateTime, UUID, UUID, UUID, String[], Boolean, OffsetDateTime, String, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.audit_seq</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setAuditSeq(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.audit_seq</code>.
     */
    @Nonnull
    public Long getAuditSeq() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.audit_createdon</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setAuditCreatedon(@Nonnull OffsetDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.audit_createdon</code>.
     */
    @Nonnull
    public OffsetDateTime getAuditCreatedon() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.audit_createdby</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setAuditCreatedby(@Nonnull String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.audit_createdby</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditCreatedby() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.audit_operation</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setAuditOperation(@Nonnull String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.audit_operation</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditOperation() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.audit_type</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setAuditType(@Nonnull String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.audit_type</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public._audit_log_student_questionnaire.id</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setId(@Nonnull UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public._audit_log_student_questionnaire.id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public._audit_log_student_questionnaire.version</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setVersion(@Nonnull OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public._audit_log_student_questionnaire.version</code>.
     */
    @NotNull
    @Nonnull
    public OffsetDateTime getVersion() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.title_i18n_id</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setTitleI18nId(@Nullable UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.title_i18n_id</code>.
     */
    @Nullable
    public UUID getTitleI18nId() {
        return (UUID) get(7);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.sub_title_i18n_id</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setSubTitleI18nId(@Nullable UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.sub_title_i18n_id</code>.
     */
    @Nullable
    public UUID getSubTitleI18nId() {
        return (UUID) get(8);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.description_i18n_id</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setDescriptionI18nId(@Nullable UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.description_i18n_id</code>.
     */
    @Nullable
    public UUID getDescriptionI18nId() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public._audit_log_student_questionnaire.sections</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setSections(@Nullable String[] value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public._audit_log_student_questionnaire.sections</code>.
     */
    @Nullable
    public String[] getSections() {
        return (String[]) get(10);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.mandatory_on_new_join_student</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setMandatoryOnNewJoinStudent(@Nullable Boolean value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.mandatory_on_new_join_student</code>.
     */
    @Nullable
    public Boolean getMandatoryOnNewJoinStudent() {
        return (Boolean) get(11);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.created_on</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setCreatedOn(@Nullable OffsetDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.created_on</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.created_by</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setCreatedBy(@Nullable String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.created_by</code>.
     */
    @Nullable
    public String getCreatedBy() {
        return (String) get(13);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.updated_on</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setUpdatedOn(@Nullable OffsetDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.updated_on</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedOn() {
        return (OffsetDateTime) get(14);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_questionnaire.updated_by</code>.
     */
    public _AuditLogStudentQuestionnaireRecord setUpdatedBy(@Nullable String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_questionnaire.updated_by</code>.
     */
    @Nullable
    public String getUpdatedBy() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row16<Long, OffsetDateTime, String, String, String, UUID, OffsetDateTime, UUID, UUID, UUID, String[], Boolean, OffsetDateTime, String, OffsetDateTime, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row16<Long, OffsetDateTime, String, String, String, UUID, OffsetDateTime, UUID, UUID, UUID, String[], Boolean, OffsetDateTime, String, OffsetDateTime, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Long> field1() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.AUDIT_SEQ;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field2() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.AUDIT_CREATEDON;
    }

    @Override
    @Nonnull
    public Field<String> field3() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.AUDIT_CREATEDBY;
    }

    @Override
    @Nonnull
    public Field<String> field4() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.AUDIT_OPERATION;
    }

    @Override
    @Nonnull
    public Field<String> field5() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.AUDIT_TYPE;
    }

    @Override
    @Nonnull
    public Field<UUID> field6() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.ID;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field7() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.VERSION;
    }

    @Override
    @Nonnull
    public Field<UUID> field8() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.TITLE_I18N_ID;
    }

    @Override
    @Nonnull
    public Field<UUID> field9() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.SUB_TITLE_I18N_ID;
    }

    @Override
    @Nonnull
    public Field<UUID> field10() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.DESCRIPTION_I18N_ID;
    }

    @Override
    @Nonnull
    public Field<String[]> field11() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.SECTIONS;
    }

    @Override
    @Nonnull
    public Field<Boolean> field12() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.MANDATORY_ON_NEW_JOIN_STUDENT;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field13() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.CREATED_ON;
    }

    @Override
    @Nonnull
    public Field<String> field14() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.CREATED_BY;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field15() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.UPDATED_ON;
    }

    @Override
    @Nonnull
    public Field<String> field16() {
        return _AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE.UPDATED_BY;
    }

    @Override
    @Nonnull
    public Long component1() {
        return getAuditSeq();
    }

    @Override
    @Nonnull
    public OffsetDateTime component2() {
        return getAuditCreatedon();
    }

    @Override
    @Nonnull
    public String component3() {
        return getAuditCreatedby();
    }

    @Override
    @Nonnull
    public String component4() {
        return getAuditOperation();
    }

    @Override
    @Nonnull
    public String component5() {
        return getAuditType();
    }

    @Override
    @Nonnull
    public UUID component6() {
        return getId();
    }

    @Override
    @Nonnull
    public OffsetDateTime component7() {
        return getVersion();
    }

    @Override
    @Nullable
    public UUID component8() {
        return getTitleI18nId();
    }

    @Override
    @Nullable
    public UUID component9() {
        return getSubTitleI18nId();
    }

    @Override
    @Nullable
    public UUID component10() {
        return getDescriptionI18nId();
    }

    @Override
    @Nullable
    public String[] component11() {
        return getSections();
    }

    @Override
    @Nullable
    public Boolean component12() {
        return getMandatoryOnNewJoinStudent();
    }

    @Override
    @Nullable
    public OffsetDateTime component13() {
        return getCreatedOn();
    }

    @Override
    @Nullable
    public String component14() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public OffsetDateTime component15() {
        return getUpdatedOn();
    }

    @Override
    @Nullable
    public String component16() {
        return getUpdatedBy();
    }

    @Override
    @Nonnull
    public Long value1() {
        return getAuditSeq();
    }

    @Override
    @Nonnull
    public OffsetDateTime value2() {
        return getAuditCreatedon();
    }

    @Override
    @Nonnull
    public String value3() {
        return getAuditCreatedby();
    }

    @Override
    @Nonnull
    public String value4() {
        return getAuditOperation();
    }

    @Override
    @Nonnull
    public String value5() {
        return getAuditType();
    }

    @Override
    @Nonnull
    public UUID value6() {
        return getId();
    }

    @Override
    @Nonnull
    public OffsetDateTime value7() {
        return getVersion();
    }

    @Override
    @Nullable
    public UUID value8() {
        return getTitleI18nId();
    }

    @Override
    @Nullable
    public UUID value9() {
        return getSubTitleI18nId();
    }

    @Override
    @Nullable
    public UUID value10() {
        return getDescriptionI18nId();
    }

    @Override
    @Nullable
    public String[] value11() {
        return getSections();
    }

    @Override
    @Nullable
    public Boolean value12() {
        return getMandatoryOnNewJoinStudent();
    }

    @Override
    @Nullable
    public OffsetDateTime value13() {
        return getCreatedOn();
    }

    @Override
    @Nullable
    public String value14() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public OffsetDateTime value15() {
        return getUpdatedOn();
    }

    @Override
    @Nullable
    public String value16() {
        return getUpdatedBy();
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value1(@Nonnull Long value) {
        setAuditSeq(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value2(@Nonnull OffsetDateTime value) {
        setAuditCreatedon(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value3(@Nonnull String value) {
        setAuditCreatedby(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value4(@Nonnull String value) {
        setAuditOperation(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value5(@Nonnull String value) {
        setAuditType(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value6(@Nonnull UUID value) {
        setId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value7(@Nonnull OffsetDateTime value) {
        setVersion(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value8(@Nullable UUID value) {
        setTitleI18nId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value9(@Nullable UUID value) {
        setSubTitleI18nId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value10(@Nullable UUID value) {
        setDescriptionI18nId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value11(@Nullable String[] value) {
        setSections(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value12(@Nullable Boolean value) {
        setMandatoryOnNewJoinStudent(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value13(@Nullable OffsetDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value14(@Nullable String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value15(@Nullable OffsetDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord value16(@Nullable String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentQuestionnaireRecord values(@Nonnull Long value1, @Nonnull OffsetDateTime value2, @Nonnull String value3, @Nonnull String value4, @Nonnull String value5, @Nonnull UUID value6, @Nonnull OffsetDateTime value7, @Nullable UUID value8, @Nullable UUID value9, @Nullable UUID value10, @Nullable String[] value11, @Nullable Boolean value12, @Nullable OffsetDateTime value13, @Nullable String value14, @Nullable OffsetDateTime value15, @Nullable String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _AuditLogStudentQuestionnaireRecord
     */
    public _AuditLogStudentQuestionnaireRecord() {
        super(_AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE);
    }

    /**
     * Create a detached, initialised _AuditLogStudentQuestionnaireRecord
     */
    @ConstructorProperties({ "auditSeq", "auditCreatedon", "auditCreatedby", "auditOperation", "auditType", "id", "version", "titleI18nId", "subTitleI18nId", "descriptionI18nId", "sections", "mandatoryOnNewJoinStudent", "createdOn", "createdBy", "updatedOn", "updatedBy" })
    public _AuditLogStudentQuestionnaireRecord(@Nonnull Long auditSeq, @Nonnull OffsetDateTime auditCreatedon, @Nonnull String auditCreatedby, @Nonnull String auditOperation, @Nonnull String auditType, @Nonnull UUID id, @Nonnull OffsetDateTime version, @Nullable UUID titleI18nId, @Nullable UUID subTitleI18nId, @Nullable UUID descriptionI18nId, @Nullable String[] sections, @Nullable Boolean mandatoryOnNewJoinStudent, @Nullable OffsetDateTime createdOn, @Nullable String createdBy, @Nullable OffsetDateTime updatedOn, @Nullable String updatedBy) {
        super(_AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE);

        setAuditSeq(auditSeq);
        setAuditCreatedon(auditCreatedon);
        setAuditCreatedby(auditCreatedby);
        setAuditOperation(auditOperation);
        setAuditType(auditType);
        setId(id);
        setVersion(version);
        setTitleI18nId(titleI18nId);
        setSubTitleI18nId(subTitleI18nId);
        setDescriptionI18nId(descriptionI18nId);
        setSections(sections);
        setMandatoryOnNewJoinStudent(mandatoryOnNewJoinStudent);
        setCreatedOn(createdOn);
        setCreatedBy(createdBy);
        setUpdatedOn(updatedOn);
        setUpdatedBy(updatedBy);
    }

    /**
     * Create a detached, initialised _AuditLogStudentQuestionnaireRecord
     */
    public _AuditLogStudentQuestionnaireRecord(_AuditLogStudentQuestionnairePojo value) {
        super(_AuditLogStudentQuestionnaireTable._AUDIT_LOG_STUDENT_QUESTIONNAIRE);

        if (value != null) {
            setAuditSeq(value.getAuditSeq());
            setAuditCreatedon(value.getAuditCreatedon());
            setAuditCreatedby(value.getAuditCreatedby());
            setAuditOperation(value.getAuditOperation());
            setAuditType(value.getAuditType());
            setId(value.getId());
            setVersion(value.getVersion());
            setTitleI18nId(value.getTitleI18nId());
            setSubTitleI18nId(value.getSubTitleI18nId());
            setDescriptionI18nId(value.getDescriptionI18nId());
            setSections(value.getSections());
            setMandatoryOnNewJoinStudent(value.getMandatoryOnNewJoinStudent());
            setCreatedOn(value.getCreatedOn());
            setCreatedBy(value.getCreatedBy());
            setUpdatedOn(value.getUpdatedOn());
            setUpdatedBy(value.getUpdatedBy());
        }
    }
}
