/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.records;


import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;

import unid.jooqMono.model.tables._AuditLogStudentProfilePredictedGradeTable;
import unid.jooqMono.model.tables.pojos._AuditLogStudentProfilePredictedGradePojo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class _AuditLogStudentProfilePredictedGradeRecord extends TableRecordImpl<_AuditLogStudentProfilePredictedGradeRecord> implements Record13<Long, OffsetDateTime, String, String, String, UUID, UUID, UUID, String, OffsetDateTime, String, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.audit_seq</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setAuditSeq(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.audit_seq</code>.
     */
    @Nonnull
    public Long getAuditSeq() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.audit_createdon</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setAuditCreatedon(@Nonnull OffsetDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.audit_createdon</code>.
     */
    @Nonnull
    public OffsetDateTime getAuditCreatedon() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.audit_createdby</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setAuditCreatedby(@Nonnull String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.audit_createdby</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditCreatedby() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.audit_operation</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setAuditOperation(@Nonnull String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.audit_operation</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditOperation() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.audit_type</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setAuditType(@Nonnull String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.audit_type</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditType() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.id</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setId(@Nonnull UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getId() {
        return (UUID) get(5);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.student_profile_id</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setStudentProfileId(@Nonnull UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.student_profile_id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getStudentProfileId() {
        return (UUID) get(6);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.academic_subject_id</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setAcademicSubjectId(@Nonnull UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.academic_subject_id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getAcademicSubjectId() {
        return (UUID) get(7);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.grade</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setGrade(@Nonnull String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.grade</code>.
     */
    @NotNull
    @Nonnull
    public String getGrade() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.created_on</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setCreatedOn(@Nullable OffsetDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.created_on</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.created_by</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setCreatedBy(@Nullable String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.created_by</code>.
     */
    @Nullable
    public String getCreatedBy() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.updated_on</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setUpdatedOn(@Nullable OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.updated_on</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedOn() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for
     * <code>public._audit_log_student_profile_predicted_grade.updated_by</code>.
     */
    public _AuditLogStudentProfilePredictedGradeRecord setUpdatedBy(@Nullable String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_student_profile_predicted_grade.updated_by</code>.
     */
    @Nullable
    public String getUpdatedBy() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row13<Long, OffsetDateTime, String, String, String, UUID, UUID, UUID, String, OffsetDateTime, String, OffsetDateTime, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row13<Long, OffsetDateTime, String, String, String, UUID, UUID, UUID, String, OffsetDateTime, String, OffsetDateTime, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Long> field1() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.AUDIT_SEQ;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field2() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.AUDIT_CREATEDON;
    }

    @Override
    @Nonnull
    public Field<String> field3() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.AUDIT_CREATEDBY;
    }

    @Override
    @Nonnull
    public Field<String> field4() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.AUDIT_OPERATION;
    }

    @Override
    @Nonnull
    public Field<String> field5() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.AUDIT_TYPE;
    }

    @Override
    @Nonnull
    public Field<UUID> field6() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.ID;
    }

    @Override
    @Nonnull
    public Field<UUID> field7() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.STUDENT_PROFILE_ID;
    }

    @Override
    @Nonnull
    public Field<UUID> field8() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.ACADEMIC_SUBJECT_ID;
    }

    @Override
    @Nonnull
    public Field<String> field9() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.GRADE;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field10() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.CREATED_ON;
    }

    @Override
    @Nonnull
    public Field<String> field11() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.CREATED_BY;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field12() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.UPDATED_ON;
    }

    @Override
    @Nonnull
    public Field<String> field13() {
        return _AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE.UPDATED_BY;
    }

    @Override
    @Nonnull
    public Long component1() {
        return getAuditSeq();
    }

    @Override
    @Nonnull
    public OffsetDateTime component2() {
        return getAuditCreatedon();
    }

    @Override
    @Nonnull
    public String component3() {
        return getAuditCreatedby();
    }

    @Override
    @Nonnull
    public String component4() {
        return getAuditOperation();
    }

    @Override
    @Nonnull
    public String component5() {
        return getAuditType();
    }

    @Override
    @Nonnull
    public UUID component6() {
        return getId();
    }

    @Override
    @Nonnull
    public UUID component7() {
        return getStudentProfileId();
    }

    @Override
    @Nonnull
    public UUID component8() {
        return getAcademicSubjectId();
    }

    @Override
    @Nonnull
    public String component9() {
        return getGrade();
    }

    @Override
    @Nullable
    public OffsetDateTime component10() {
        return getCreatedOn();
    }

    @Override
    @Nullable
    public String component11() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public OffsetDateTime component12() {
        return getUpdatedOn();
    }

    @Override
    @Nullable
    public String component13() {
        return getUpdatedBy();
    }

    @Override
    @Nonnull
    public Long value1() {
        return getAuditSeq();
    }

    @Override
    @Nonnull
    public OffsetDateTime value2() {
        return getAuditCreatedon();
    }

    @Override
    @Nonnull
    public String value3() {
        return getAuditCreatedby();
    }

    @Override
    @Nonnull
    public String value4() {
        return getAuditOperation();
    }

    @Override
    @Nonnull
    public String value5() {
        return getAuditType();
    }

    @Override
    @Nonnull
    public UUID value6() {
        return getId();
    }

    @Override
    @Nonnull
    public UUID value7() {
        return getStudentProfileId();
    }

    @Override
    @Nonnull
    public UUID value8() {
        return getAcademicSubjectId();
    }

    @Override
    @Nonnull
    public String value9() {
        return getGrade();
    }

    @Override
    @Nullable
    public OffsetDateTime value10() {
        return getCreatedOn();
    }

    @Override
    @Nullable
    public String value11() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public OffsetDateTime value12() {
        return getUpdatedOn();
    }

    @Override
    @Nullable
    public String value13() {
        return getUpdatedBy();
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value1(@Nonnull Long value) {
        setAuditSeq(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value2(@Nonnull OffsetDateTime value) {
        setAuditCreatedon(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value3(@Nonnull String value) {
        setAuditCreatedby(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value4(@Nonnull String value) {
        setAuditOperation(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value5(@Nonnull String value) {
        setAuditType(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value6(@Nonnull UUID value) {
        setId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value7(@Nonnull UUID value) {
        setStudentProfileId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value8(@Nonnull UUID value) {
        setAcademicSubjectId(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value9(@Nonnull String value) {
        setGrade(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value10(@Nullable OffsetDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value11(@Nullable String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value12(@Nullable OffsetDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord value13(@Nullable String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    @Nonnull
    public _AuditLogStudentProfilePredictedGradeRecord values(@Nonnull Long value1, @Nonnull OffsetDateTime value2, @Nonnull String value3, @Nonnull String value4, @Nonnull String value5, @Nonnull UUID value6, @Nonnull UUID value7, @Nonnull UUID value8, @Nonnull String value9, @Nullable OffsetDateTime value10, @Nullable String value11, @Nullable OffsetDateTime value12, @Nullable String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _AuditLogStudentProfilePredictedGradeRecord
     */
    public _AuditLogStudentProfilePredictedGradeRecord() {
        super(_AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE);
    }

    /**
     * Create a detached, initialised
     * _AuditLogStudentProfilePredictedGradeRecord
     */
    @ConstructorProperties({ "auditSeq", "auditCreatedon", "auditCreatedby", "auditOperation", "auditType", "id", "studentProfileId", "academicSubjectId", "grade", "createdOn", "createdBy", "updatedOn", "updatedBy" })
    public _AuditLogStudentProfilePredictedGradeRecord(@Nonnull Long auditSeq, @Nonnull OffsetDateTime auditCreatedon, @Nonnull String auditCreatedby, @Nonnull String auditOperation, @Nonnull String auditType, @Nonnull UUID id, @Nonnull UUID studentProfileId, @Nonnull UUID academicSubjectId, @Nonnull String grade, @Nullable OffsetDateTime createdOn, @Nullable String createdBy, @Nullable OffsetDateTime updatedOn, @Nullable String updatedBy) {
        super(_AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE);

        setAuditSeq(auditSeq);
        setAuditCreatedon(auditCreatedon);
        setAuditCreatedby(auditCreatedby);
        setAuditOperation(auditOperation);
        setAuditType(auditType);
        setId(id);
        setStudentProfileId(studentProfileId);
        setAcademicSubjectId(academicSubjectId);
        setGrade(grade);
        setCreatedOn(createdOn);
        setCreatedBy(createdBy);
        setUpdatedOn(updatedOn);
        setUpdatedBy(updatedBy);
    }

    /**
     * Create a detached, initialised
     * _AuditLogStudentProfilePredictedGradeRecord
     */
    public _AuditLogStudentProfilePredictedGradeRecord(_AuditLogStudentProfilePredictedGradePojo value) {
        super(_AuditLogStudentProfilePredictedGradeTable._AUDIT_LOG_STUDENT_PROFILE_PREDICTED_GRADE);

        if (value != null) {
            setAuditSeq(value.getAuditSeq());
            setAuditCreatedon(value.getAuditCreatedon());
            setAuditCreatedby(value.getAuditCreatedby());
            setAuditOperation(value.getAuditOperation());
            setAuditType(value.getAuditType());
            setId(value.getId());
            setStudentProfileId(value.getStudentProfileId());
            setAcademicSubjectId(value.getAcademicSubjectId());
            setGrade(value.getGrade());
            setCreatedOn(value.getCreatedOn());
            setCreatedBy(value.getCreatedBy());
            setUpdatedOn(value.getUpdatedOn());
            setUpdatedBy(value.getUpdatedBy());
        }
    }
}
