/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.records;


import java.beans.ConstructorProperties;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import unid.jooqMono.model.tables.EcaProfileSectionTable;
import unid.jooqMono.model.tables.pojos.EcaProfileSectionPojo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class EcaProfileSectionRecord extends UpdatableRecordImpl<EcaProfileSectionRecord> implements Record3<UUID, UUID, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.eca_profile_section.id</code>.
     */
    public EcaProfileSectionRecord setId(@Nonnull UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.eca_profile_section.id</code>.
     */
    @Nonnull
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.eca_profile_section.section_i18n_id</code>.
     */
    public EcaProfileSectionRecord setSectionI18nId(@Nullable UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.eca_profile_section.section_i18n_id</code>.
     */
    @Nullable
    public UUID getSectionI18nId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.eca_profile_section.sort</code>.
     */
    public EcaProfileSectionRecord setSort(@Nullable Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.eca_profile_section.sort</code>.
     */
    @Nullable
    public Integer getSort() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row3<UUID, UUID, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row3<UUID, UUID, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<UUID> field1() {
        return EcaProfileSectionTable.ECA_PROFILE_SECTION.ID;
    }

    @Override
    @Nonnull
    public Field<UUID> field2() {
        return EcaProfileSectionTable.ECA_PROFILE_SECTION.SECTION_I18N_ID;
    }

    @Override
    @Nonnull
    public Field<Integer> field3() {
        return EcaProfileSectionTable.ECA_PROFILE_SECTION.SORT;
    }

    @Override
    @Nonnull
    public UUID component1() {
        return getId();
    }

    @Override
    @Nullable
    public UUID component2() {
        return getSectionI18nId();
    }

    @Override
    @Nullable
    public Integer component3() {
        return getSort();
    }

    @Override
    @Nonnull
    public UUID value1() {
        return getId();
    }

    @Override
    @Nullable
    public UUID value2() {
        return getSectionI18nId();
    }

    @Override
    @Nullable
    public Integer value3() {
        return getSort();
    }

    @Override
    @Nonnull
    public EcaProfileSectionRecord value1(@Nonnull UUID value) {
        setId(value);
        return this;
    }

    @Override
    @Nonnull
    public EcaProfileSectionRecord value2(@Nullable UUID value) {
        setSectionI18nId(value);
        return this;
    }

    @Override
    @Nonnull
    public EcaProfileSectionRecord value3(@Nullable Integer value) {
        setSort(value);
        return this;
    }

    @Override
    @Nonnull
    public EcaProfileSectionRecord values(@Nonnull UUID value1, @Nullable UUID value2, @Nullable Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EcaProfileSectionRecord
     */
    public EcaProfileSectionRecord() {
        super(EcaProfileSectionTable.ECA_PROFILE_SECTION);
    }

    /**
     * Create a detached, initialised EcaProfileSectionRecord
     */
    @ConstructorProperties({ "id", "sectionI18nId", "sort" })
    public EcaProfileSectionRecord(@Nonnull UUID id, @Nullable UUID sectionI18nId, @Nullable Integer sort) {
        super(EcaProfileSectionTable.ECA_PROFILE_SECTION);

        setId(id);
        setSectionI18nId(sectionI18nId);
        setSort(sort);
    }

    /**
     * Create a detached, initialised EcaProfileSectionRecord
     */
    public EcaProfileSectionRecord(EcaProfileSectionPojo value) {
        super(EcaProfileSectionTable.ECA_PROFILE_SECTION);

        if (value != null) {
            setId(value.getId());
            setSectionI18nId(value.getSectionI18nId());
            setSort(value.getSort());
        }
    }
}
