/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.records;


import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;

import unid.jooqMono.model.enums.UserRoleEnum;
import unid.jooqMono.model.tables.UserTable;
import unid.jooqMono.model.tables.pojos.UserPojo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record15<UUID, UUID, UUID, UserRoleEnum, String, String, String, Boolean, String, String, Boolean, OffsetDateTime, String, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user.id</code>.
     */
    public UserRecord setId(@Nonnull UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user.id</code>.
     */
    @Nonnull
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.user.last_name_i18n_id</code>.
     */
    public UserRecord setLastNameI18nId(@Nullable UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user.last_name_i18n_id</code>.
     */
    @Nullable
    public UUID getLastNameI18nId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.user.fist_name_i18n_id</code>.
     */
    public UserRecord setFistNameI18nId(@Nullable UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user.fist_name_i18n_id</code>.
     */
    @Nullable
    public UUID getFistNameI18nId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.user.user_role</code>.
     */
    public UserRecord setUserRole(@Nonnull UserRoleEnum value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user.user_role</code>.
     */
    @NotNull
    @Nonnull
    public UserRoleEnum getUserRole() {
        return (UserRoleEnum) get(3);
    }

    /**
     * Setter for <code>public.user.login_id</code>.
     */
    public UserRecord setLoginId(@Nullable String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user.login_id</code>.
     */
    @Nullable
    public String getLoginId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user.login_password</code>.
     */
    public UserRecord setLoginPassword(@Nullable String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.user.login_password</code>.
     */
    @Nullable
    public String getLoginPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.user.email</code>.
     */
    public UserRecord setEmail(@Nullable String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.user.email</code>.
     */
    @Nullable
    public String getEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.user.email_verified</code>.
     */
    public UserRecord setEmailVerified(@Nullable Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.user.email_verified</code>.
     */
    @Nullable
    public Boolean getEmailVerified() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.user.google_client_id</code>.
     */
    public UserRecord setGoogleClientId(@Nullable String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.user.google_client_id</code>.
     */
    @Nullable
    public String getGoogleClientId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.user.tencent_wechat_client_id</code>.
     */
    public UserRecord setTencentWechatClientId(@Nullable String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.user.tencent_wechat_client_id</code>.
     */
    @Nullable
    public String getTencentWechatClientId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.user.deleted</code>.
     */
    public UserRecord setDeleted(@Nullable Boolean value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.user.deleted</code>.
     */
    @Nullable
    public Boolean getDeleted() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.user.created_on</code>.
     */
    public UserRecord setCreatedOn(@Nullable OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.user.created_on</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.user.created_by</code>.
     */
    public UserRecord setCreatedBy(@Nullable String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.user.created_by</code>.
     */
    @Nullable
    public String getCreatedBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.user.updated_on</code>.
     */
    public UserRecord setUpdatedOn(@Nullable OffsetDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.user.updated_on</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedOn() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>public.user.updated_by</code>.
     */
    public UserRecord setUpdatedBy(@Nullable String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.user.updated_by</code>.
     */
    @Nullable
    public String getUpdatedBy() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row15<UUID, UUID, UUID, UserRoleEnum, String, String, String, Boolean, String, String, Boolean, OffsetDateTime, String, OffsetDateTime, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row15<UUID, UUID, UUID, UserRoleEnum, String, String, String, Boolean, String, String, Boolean, OffsetDateTime, String, OffsetDateTime, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<UUID> field1() {
        return UserTable.USER.ID;
    }

    @Override
    @Nonnull
    public Field<UUID> field2() {
        return UserTable.USER.LAST_NAME_I18N_ID;
    }

    @Override
    @Nonnull
    public Field<UUID> field3() {
        return UserTable.USER.FIST_NAME_I18N_ID;
    }

    @Override
    @Nonnull
    public Field<UserRoleEnum> field4() {
        return UserTable.USER.USER_ROLE;
    }

    @Override
    @Nonnull
    public Field<String> field5() {
        return UserTable.USER.LOGIN_ID;
    }

    @Override
    @Nonnull
    public Field<String> field6() {
        return UserTable.USER.LOGIN_PASSWORD;
    }

    @Override
    @Nonnull
    public Field<String> field7() {
        return UserTable.USER.EMAIL;
    }

    @Override
    @Nonnull
    public Field<Boolean> field8() {
        return UserTable.USER.EMAIL_VERIFIED;
    }

    @Override
    @Nonnull
    public Field<String> field9() {
        return UserTable.USER.GOOGLE_CLIENT_ID;
    }

    @Override
    @Nonnull
    public Field<String> field10() {
        return UserTable.USER.TENCENT_WECHAT_CLIENT_ID;
    }

    @Override
    @Nonnull
    public Field<Boolean> field11() {
        return UserTable.USER.DELETED;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field12() {
        return UserTable.USER.CREATED_ON;
    }

    @Override
    @Nonnull
    public Field<String> field13() {
        return UserTable.USER.CREATED_BY;
    }

    @Override
    @Nonnull
    public Field<OffsetDateTime> field14() {
        return UserTable.USER.UPDATED_ON;
    }

    @Override
    @Nonnull
    public Field<String> field15() {
        return UserTable.USER.UPDATED_BY;
    }

    @Override
    @Nonnull
    public UUID component1() {
        return getId();
    }

    @Override
    @Nullable
    public UUID component2() {
        return getLastNameI18nId();
    }

    @Override
    @Nullable
    public UUID component3() {
        return getFistNameI18nId();
    }

    @Override
    @Nonnull
    public UserRoleEnum component4() {
        return getUserRole();
    }

    @Override
    @Nullable
    public String component5() {
        return getLoginId();
    }

    @Override
    @Nullable
    public String component6() {
        return getLoginPassword();
    }

    @Override
    @Nullable
    public String component7() {
        return getEmail();
    }

    @Override
    @Nullable
    public Boolean component8() {
        return getEmailVerified();
    }

    @Override
    @Nullable
    public String component9() {
        return getGoogleClientId();
    }

    @Override
    @Nullable
    public String component10() {
        return getTencentWechatClientId();
    }

    @Override
    @Nullable
    public Boolean component11() {
        return getDeleted();
    }

    @Override
    @Nullable
    public OffsetDateTime component12() {
        return getCreatedOn();
    }

    @Override
    @Nullable
    public String component13() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public OffsetDateTime component14() {
        return getUpdatedOn();
    }

    @Override
    @Nullable
    public String component15() {
        return getUpdatedBy();
    }

    @Override
    @Nonnull
    public UUID value1() {
        return getId();
    }

    @Override
    @Nullable
    public UUID value2() {
        return getLastNameI18nId();
    }

    @Override
    @Nullable
    public UUID value3() {
        return getFistNameI18nId();
    }

    @Override
    @Nonnull
    public UserRoleEnum value4() {
        return getUserRole();
    }

    @Override
    @Nullable
    public String value5() {
        return getLoginId();
    }

    @Override
    @Nullable
    public String value6() {
        return getLoginPassword();
    }

    @Override
    @Nullable
    public String value7() {
        return getEmail();
    }

    @Override
    @Nullable
    public Boolean value8() {
        return getEmailVerified();
    }

    @Override
    @Nullable
    public String value9() {
        return getGoogleClientId();
    }

    @Override
    @Nullable
    public String value10() {
        return getTencentWechatClientId();
    }

    @Override
    @Nullable
    public Boolean value11() {
        return getDeleted();
    }

    @Override
    @Nullable
    public OffsetDateTime value12() {
        return getCreatedOn();
    }

    @Override
    @Nullable
    public String value13() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public OffsetDateTime value14() {
        return getUpdatedOn();
    }

    @Override
    @Nullable
    public String value15() {
        return getUpdatedBy();
    }

    @Override
    @Nonnull
    public UserRecord value1(@Nonnull UUID value) {
        setId(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value2(@Nullable UUID value) {
        setLastNameI18nId(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value3(@Nullable UUID value) {
        setFistNameI18nId(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value4(@Nonnull UserRoleEnum value) {
        setUserRole(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value5(@Nullable String value) {
        setLoginId(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value6(@Nullable String value) {
        setLoginPassword(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value7(@Nullable String value) {
        setEmail(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value8(@Nullable Boolean value) {
        setEmailVerified(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value9(@Nullable String value) {
        setGoogleClientId(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value10(@Nullable String value) {
        setTencentWechatClientId(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value11(@Nullable Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value12(@Nullable OffsetDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value13(@Nullable String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value14(@Nullable OffsetDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord value15(@Nullable String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    @Nonnull
    public UserRecord values(@Nonnull UUID value1, @Nullable UUID value2, @Nullable UUID value3, @Nonnull UserRoleEnum value4, @Nullable String value5, @Nullable String value6, @Nullable String value7, @Nullable Boolean value8, @Nullable String value9, @Nullable String value10, @Nullable Boolean value11, @Nullable OffsetDateTime value12, @Nullable String value13, @Nullable OffsetDateTime value14, @Nullable String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(UserTable.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    @ConstructorProperties({ "id", "lastNameI18nId", "fistNameI18nId", "userRole", "loginId", "loginPassword", "email", "emailVerified", "googleClientId", "tencentWechatClientId", "deleted", "createdOn", "createdBy", "updatedOn", "updatedBy" })
    public UserRecord(@Nonnull UUID id, @Nullable UUID lastNameI18nId, @Nullable UUID fistNameI18nId, @Nonnull UserRoleEnum userRole, @Nullable String loginId, @Nullable String loginPassword, @Nullable String email, @Nullable Boolean emailVerified, @Nullable String googleClientId, @Nullable String tencentWechatClientId, @Nullable Boolean deleted, @Nullable OffsetDateTime createdOn, @Nullable String createdBy, @Nullable OffsetDateTime updatedOn, @Nullable String updatedBy) {
        super(UserTable.USER);

        setId(id);
        setLastNameI18nId(lastNameI18nId);
        setFistNameI18nId(fistNameI18nId);
        setUserRole(userRole);
        setLoginId(loginId);
        setLoginPassword(loginPassword);
        setEmail(email);
        setEmailVerified(emailVerified);
        setGoogleClientId(googleClientId);
        setTencentWechatClientId(tencentWechatClientId);
        setDeleted(deleted);
        setCreatedOn(createdOn);
        setCreatedBy(createdBy);
        setUpdatedOn(updatedOn);
        setUpdatedBy(updatedBy);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(UserPojo value) {
        super(UserTable.USER);

        if (value != null) {
            setId(value.getId());
            setLastNameI18nId(value.getLastNameI18nId());
            setFistNameI18nId(value.getFistNameI18nId());
            setUserRole(value.getUserRole());
            setLoginId(value.getLoginId());
            setLoginPassword(value.getLoginPassword());
            setEmail(value.getEmail());
            setEmailVerified(value.getEmailVerified());
            setGoogleClientId(value.getGoogleClientId());
            setTencentWechatClientId(value.getTencentWechatClientId());
            setDeleted(value.getDeleted());
            setCreatedOn(value.getCreatedOn());
            setCreatedBy(value.getCreatedBy());
            setUpdatedOn(value.getUpdatedOn());
            setUpdatedBy(value.getUpdatedBy());
        }
    }
}
