/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;

import unid.jooqMono.model.enums.ApplicationApprovalEnum;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class _AuditLogEducatorProfilePojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long                    auditSeq;
    private OffsetDateTime          auditCreatedon;
    private String                  auditCreatedby;
    private String                  auditOperation;
    private String                  auditType;
    private UUID                    id;
    private UUID                    userId;
    private ApplicationApprovalEnum applicationApproval;
    private String                  microsoftId;
    private String                  microsoftEmail;
    private UUID                    countryId;
    private String                  profilePicture;
    private String                  phoneCountryCode;
    private String                  phone;
    private Integer                 hourlyRate;
    private UUID                    universityId;
    private UUID                    universityEducationLevelId;
    private UUID                    universityIdentityId;
    private OffsetDateTime          createdOn;
    private String                  createdBy;
    private OffsetDateTime          updatedOn;
    private String                  updatedBy;

    public _AuditLogEducatorProfilePojo() {}

    public _AuditLogEducatorProfilePojo(_AuditLogEducatorProfilePojo value) {
        this.auditSeq = value.auditSeq;
        this.auditCreatedon = value.auditCreatedon;
        this.auditCreatedby = value.auditCreatedby;
        this.auditOperation = value.auditOperation;
        this.auditType = value.auditType;
        this.id = value.id;
        this.userId = value.userId;
        this.applicationApproval = value.applicationApproval;
        this.microsoftId = value.microsoftId;
        this.microsoftEmail = value.microsoftEmail;
        this.countryId = value.countryId;
        this.profilePicture = value.profilePicture;
        this.phoneCountryCode = value.phoneCountryCode;
        this.phone = value.phone;
        this.hourlyRate = value.hourlyRate;
        this.universityId = value.universityId;
        this.universityEducationLevelId = value.universityEducationLevelId;
        this.universityIdentityId = value.universityIdentityId;
        this.createdOn = value.createdOn;
        this.createdBy = value.createdBy;
        this.updatedOn = value.updatedOn;
        this.updatedBy = value.updatedBy;
    }

    @ConstructorProperties({ "auditSeq", "auditCreatedon", "auditCreatedby", "auditOperation", "auditType", "id", "userId", "applicationApproval", "microsoftId", "microsoftEmail", "countryId", "profilePicture", "phoneCountryCode", "phone", "hourlyRate", "universityId", "universityEducationLevelId", "universityIdentityId", "createdOn", "createdBy", "updatedOn", "updatedBy" })
    public _AuditLogEducatorProfilePojo(
        @Nonnull Long                    auditSeq,
        @Nonnull OffsetDateTime          auditCreatedon,
        @Nonnull String                  auditCreatedby,
        @Nonnull String                  auditOperation,
        @Nonnull String                  auditType,
        @Nonnull UUID                    id,
        @Nonnull UUID                    userId,
        @Nonnull ApplicationApprovalEnum applicationApproval,
        @Nullable String                  microsoftId,
        @Nullable String                  microsoftEmail,
        @Nullable UUID                    countryId,
        @Nullable String                  profilePicture,
        @Nullable String                  phoneCountryCode,
        @Nullable String                  phone,
        @Nullable Integer                 hourlyRate,
        @Nullable UUID                    universityId,
        @Nullable UUID                    universityEducationLevelId,
        @Nullable UUID                    universityIdentityId,
        @Nullable OffsetDateTime          createdOn,
        @Nullable String                  createdBy,
        @Nullable OffsetDateTime          updatedOn,
        @Nullable String                  updatedBy
    ) {
        this.auditSeq = auditSeq;
        this.auditCreatedon = auditCreatedon;
        this.auditCreatedby = auditCreatedby;
        this.auditOperation = auditOperation;
        this.auditType = auditType;
        this.id = id;
        this.userId = userId;
        this.applicationApproval = applicationApproval;
        this.microsoftId = microsoftId;
        this.microsoftEmail = microsoftEmail;
        this.countryId = countryId;
        this.profilePicture = profilePicture;
        this.phoneCountryCode = phoneCountryCode;
        this.phone = phone;
        this.hourlyRate = hourlyRate;
        this.universityId = universityId;
        this.universityEducationLevelId = universityEducationLevelId;
        this.universityIdentityId = universityIdentityId;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
        this.updatedOn = updatedOn;
        this.updatedBy = updatedBy;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.audit_seq</code>.
     */
    @Nonnull
    public Long getAuditSeq() {
        return this.auditSeq;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.audit_seq</code>.
     */
    public _AuditLogEducatorProfilePojo setAuditSeq(@Nonnull Long auditSeq) {
        this.auditSeq = auditSeq;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_educator_profile.audit_createdon</code>.
     */
    @Nonnull
    public OffsetDateTime getAuditCreatedon() {
        return this.auditCreatedon;
    }

    /**
     * Setter for
     * <code>public._audit_log_educator_profile.audit_createdon</code>.
     */
    public _AuditLogEducatorProfilePojo setAuditCreatedon(@Nonnull OffsetDateTime auditCreatedon) {
        this.auditCreatedon = auditCreatedon;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_educator_profile.audit_createdby</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditCreatedby() {
        return this.auditCreatedby;
    }

    /**
     * Setter for
     * <code>public._audit_log_educator_profile.audit_createdby</code>.
     */
    public _AuditLogEducatorProfilePojo setAuditCreatedby(@Nonnull String auditCreatedby) {
        this.auditCreatedby = auditCreatedby;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_educator_profile.audit_operation</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditOperation() {
        return this.auditOperation;
    }

    /**
     * Setter for
     * <code>public._audit_log_educator_profile.audit_operation</code>.
     */
    public _AuditLogEducatorProfilePojo setAuditOperation(@Nonnull String auditOperation) {
        this.auditOperation = auditOperation;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.audit_type</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditType() {
        return this.auditType;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.audit_type</code>.
     */
    public _AuditLogEducatorProfilePojo setAuditType(@Nonnull String auditType) {
        this.auditType = auditType;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.id</code>.
     */
    public _AuditLogEducatorProfilePojo setId(@Nonnull UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.user_id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.user_id</code>.
     */
    public _AuditLogEducatorProfilePojo setUserId(@Nonnull UUID userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_educator_profile.application_approval</code>.
     */
    @NotNull
    @Nonnull
    public ApplicationApprovalEnum getApplicationApproval() {
        return this.applicationApproval;
    }

    /**
     * Setter for
     * <code>public._audit_log_educator_profile.application_approval</code>.
     */
    public _AuditLogEducatorProfilePojo setApplicationApproval(@Nonnull ApplicationApprovalEnum applicationApproval) {
        this.applicationApproval = applicationApproval;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.microsoft_id</code>.
     */
    @Nullable
    public String getMicrosoftId() {
        return this.microsoftId;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.microsoft_id</code>.
     */
    public _AuditLogEducatorProfilePojo setMicrosoftId(@Nullable String microsoftId) {
        this.microsoftId = microsoftId;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_educator_profile.microsoft_email</code>.
     */
    @Nullable
    public String getMicrosoftEmail() {
        return this.microsoftEmail;
    }

    /**
     * Setter for
     * <code>public._audit_log_educator_profile.microsoft_email</code>.
     */
    public _AuditLogEducatorProfilePojo setMicrosoftEmail(@Nullable String microsoftEmail) {
        this.microsoftEmail = microsoftEmail;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.country_id</code>.
     */
    @Nullable
    public UUID getCountryId() {
        return this.countryId;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.country_id</code>.
     */
    public _AuditLogEducatorProfilePojo setCountryId(@Nullable UUID countryId) {
        this.countryId = countryId;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_educator_profile.profile_picture</code>.
     */
    @Nullable
    public String getProfilePicture() {
        return this.profilePicture;
    }

    /**
     * Setter for
     * <code>public._audit_log_educator_profile.profile_picture</code>.
     */
    public _AuditLogEducatorProfilePojo setProfilePicture(@Nullable String profilePicture) {
        this.profilePicture = profilePicture;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_educator_profile.phone_country_code</code>.
     */
    @Nullable
    public String getPhoneCountryCode() {
        return this.phoneCountryCode;
    }

    /**
     * Setter for
     * <code>public._audit_log_educator_profile.phone_country_code</code>.
     */
    public _AuditLogEducatorProfilePojo setPhoneCountryCode(@Nullable String phoneCountryCode) {
        this.phoneCountryCode = phoneCountryCode;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.phone</code>.
     */
    @Nullable
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.phone</code>.
     */
    public _AuditLogEducatorProfilePojo setPhone(@Nullable String phone) {
        this.phone = phone;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.hourly_rate</code>.
     */
    @Nullable
    public Integer getHourlyRate() {
        return this.hourlyRate;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.hourly_rate</code>.
     */
    public _AuditLogEducatorProfilePojo setHourlyRate(@Nullable Integer hourlyRate) {
        this.hourlyRate = hourlyRate;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.university_id</code>.
     */
    @Nullable
    public UUID getUniversityId() {
        return this.universityId;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.university_id</code>.
     */
    public _AuditLogEducatorProfilePojo setUniversityId(@Nullable UUID universityId) {
        this.universityId = universityId;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_educator_profile.university_education_level_id</code>.
     */
    @Nullable
    public UUID getUniversityEducationLevelId() {
        return this.universityEducationLevelId;
    }

    /**
     * Setter for
     * <code>public._audit_log_educator_profile.university_education_level_id</code>.
     */
    public _AuditLogEducatorProfilePojo setUniversityEducationLevelId(@Nullable UUID universityEducationLevelId) {
        this.universityEducationLevelId = universityEducationLevelId;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_educator_profile.university_identity_id</code>.
     */
    @Nullable
    public UUID getUniversityIdentityId() {
        return this.universityIdentityId;
    }

    /**
     * Setter for
     * <code>public._audit_log_educator_profile.university_identity_id</code>.
     */
    public _AuditLogEducatorProfilePojo setUniversityIdentityId(@Nullable UUID universityIdentityId) {
        this.universityIdentityId = universityIdentityId;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.created_on</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.created_on</code>.
     */
    public _AuditLogEducatorProfilePojo setCreatedOn(@Nullable OffsetDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.created_by</code>.
     */
    @Nullable
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.created_by</code>.
     */
    public _AuditLogEducatorProfilePojo setCreatedBy(@Nullable String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.updated_on</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.updated_on</code>.
     */
    public _AuditLogEducatorProfilePojo setUpdatedOn(@Nullable OffsetDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_educator_profile.updated_by</code>.
     */
    @Nullable
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>public._audit_log_educator_profile.updated_by</code>.
     */
    public _AuditLogEducatorProfilePojo setUpdatedBy(@Nullable String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("_AuditLogEducatorProfilePojo (");

        sb.append(auditSeq);
        sb.append(", ").append(auditCreatedon);
        sb.append(", ").append(auditCreatedby);
        sb.append(", ").append(auditOperation);
        sb.append(", ").append(auditType);
        sb.append(", ").append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(applicationApproval);
        sb.append(", ").append(microsoftId);
        sb.append(", ").append(microsoftEmail);
        sb.append(", ").append(countryId);
        sb.append(", ").append(profilePicture);
        sb.append(", ").append(phoneCountryCode);
        sb.append(", ").append(phone);
        sb.append(", ").append(hourlyRate);
        sb.append(", ").append(universityId);
        sb.append(", ").append(universityEducationLevelId);
        sb.append(", ").append(universityIdentityId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }
}
