/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;

import unid.jooqMono.model.enums.AcademicSubjectResourceTypeEnum;
import unid.jooqMono.model.enums.VideoSourceEnum;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class _AuditLogAcademicSubjectResourcePojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long                            auditSeq;
    private OffsetDateTime                  auditCreatedon;
    private String                          auditCreatedby;
    private String                          auditOperation;
    private String                          auditType;
    private UUID                            id;
    private UUID                            academicSubjectId;
    private AcademicSubjectResourceTypeEnum type;
    private UUID                            titleI18nId;
    private String                          author;
    private String                          url;
    private String                          thumbnail;
    private OffsetDateTime                  createdOn;
    private String                          createdBy;
    private OffsetDateTime                  updatedOn;
    private String                          updatedBy;
    private VideoSourceEnum                 videoSource;

    public _AuditLogAcademicSubjectResourcePojo() {}

    public _AuditLogAcademicSubjectResourcePojo(_AuditLogAcademicSubjectResourcePojo value) {
        this.auditSeq = value.auditSeq;
        this.auditCreatedon = value.auditCreatedon;
        this.auditCreatedby = value.auditCreatedby;
        this.auditOperation = value.auditOperation;
        this.auditType = value.auditType;
        this.id = value.id;
        this.academicSubjectId = value.academicSubjectId;
        this.type = value.type;
        this.titleI18nId = value.titleI18nId;
        this.author = value.author;
        this.url = value.url;
        this.thumbnail = value.thumbnail;
        this.createdOn = value.createdOn;
        this.createdBy = value.createdBy;
        this.updatedOn = value.updatedOn;
        this.updatedBy = value.updatedBy;
        this.videoSource = value.videoSource;
    }

    @ConstructorProperties({ "auditSeq", "auditCreatedon", "auditCreatedby", "auditOperation", "auditType", "id", "academicSubjectId", "type", "titleI18nId", "author", "url", "thumbnail", "createdOn", "createdBy", "updatedOn", "updatedBy", "videoSource" })
    public _AuditLogAcademicSubjectResourcePojo(
        @Nonnull Long                            auditSeq,
        @Nonnull OffsetDateTime                  auditCreatedon,
        @Nonnull String                          auditCreatedby,
        @Nonnull String                          auditOperation,
        @Nonnull String                          auditType,
        @Nonnull UUID                            id,
        @Nonnull UUID                            academicSubjectId,
        @Nullable AcademicSubjectResourceTypeEnum type,
        @Nullable UUID                            titleI18nId,
        @Nullable String                          author,
        @Nullable String                          url,
        @Nullable String                          thumbnail,
        @Nullable OffsetDateTime                  createdOn,
        @Nullable String                          createdBy,
        @Nullable OffsetDateTime                  updatedOn,
        @Nullable String                          updatedBy,
        @Nullable VideoSourceEnum                 videoSource
    ) {
        this.auditSeq = auditSeq;
        this.auditCreatedon = auditCreatedon;
        this.auditCreatedby = auditCreatedby;
        this.auditOperation = auditOperation;
        this.auditType = auditType;
        this.id = id;
        this.academicSubjectId = academicSubjectId;
        this.type = type;
        this.titleI18nId = titleI18nId;
        this.author = author;
        this.url = url;
        this.thumbnail = thumbnail;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
        this.updatedOn = updatedOn;
        this.updatedBy = updatedBy;
        this.videoSource = videoSource;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.audit_seq</code>.
     */
    @Nonnull
    public Long getAuditSeq() {
        return this.auditSeq;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.audit_seq</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setAuditSeq(@Nonnull Long auditSeq) {
        this.auditSeq = auditSeq;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.audit_createdon</code>.
     */
    @Nonnull
    public OffsetDateTime getAuditCreatedon() {
        return this.auditCreatedon;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.audit_createdon</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setAuditCreatedon(@Nonnull OffsetDateTime auditCreatedon) {
        this.auditCreatedon = auditCreatedon;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.audit_createdby</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditCreatedby() {
        return this.auditCreatedby;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.audit_createdby</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setAuditCreatedby(@Nonnull String auditCreatedby) {
        this.auditCreatedby = auditCreatedby;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.audit_operation</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditOperation() {
        return this.auditOperation;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.audit_operation</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setAuditOperation(@Nonnull String auditOperation) {
        this.auditOperation = auditOperation;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.audit_type</code>.
     */
    @NotNull
    @Nonnull
    public String getAuditType() {
        return this.auditType;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.audit_type</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setAuditType(@Nonnull String auditType) {
        this.auditType = auditType;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_academic_subject_resource.id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public._audit_log_academic_subject_resource.id</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setId(@Nonnull UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.academic_subject_id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getAcademicSubjectId() {
        return this.academicSubjectId;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.academic_subject_id</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setAcademicSubjectId(@Nonnull UUID academicSubjectId) {
        this.academicSubjectId = academicSubjectId;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_academic_subject_resource.type</code>.
     */
    @Nullable
    public AcademicSubjectResourceTypeEnum getType() {
        return this.type;
    }

    /**
     * Setter for <code>public._audit_log_academic_subject_resource.type</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setType(@Nullable AcademicSubjectResourceTypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.title_i18n_id</code>.
     */
    @Nullable
    public UUID getTitleI18nId() {
        return this.titleI18nId;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.title_i18n_id</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setTitleI18nId(@Nullable UUID titleI18nId) {
        this.titleI18nId = titleI18nId;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.author</code>.
     */
    @Nullable
    public String getAuthor() {
        return this.author;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.author</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setAuthor(@Nullable String author) {
        this.author = author;
        return this;
    }

    /**
     * Getter for <code>public._audit_log_academic_subject_resource.url</code>.
     */
    @Nullable
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>public._audit_log_academic_subject_resource.url</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setUrl(@Nullable String url) {
        this.url = url;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.thumbnail</code>.
     */
    @Nullable
    public String getThumbnail() {
        return this.thumbnail;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.thumbnail</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setThumbnail(@Nullable String thumbnail) {
        this.thumbnail = thumbnail;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.created_on</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.created_on</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setCreatedOn(@Nullable OffsetDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.created_by</code>.
     */
    @Nullable
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.created_by</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setCreatedBy(@Nullable String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.updated_on</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.updated_on</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setUpdatedOn(@Nullable OffsetDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.updated_by</code>.
     */
    @Nullable
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.updated_by</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setUpdatedBy(@Nullable String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Getter for
     * <code>public._audit_log_academic_subject_resource.video_source</code>.
     */
    @Nullable
    public VideoSourceEnum getVideoSource() {
        return this.videoSource;
    }

    /**
     * Setter for
     * <code>public._audit_log_academic_subject_resource.video_source</code>.
     */
    public _AuditLogAcademicSubjectResourcePojo setVideoSource(@Nullable VideoSourceEnum videoSource) {
        this.videoSource = videoSource;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("_AuditLogAcademicSubjectResourcePojo (");

        sb.append(auditSeq);
        sb.append(", ").append(auditCreatedon);
        sb.append(", ").append(auditCreatedby);
        sb.append(", ").append(auditOperation);
        sb.append(", ").append(auditType);
        sb.append(", ").append(id);
        sb.append(", ").append(academicSubjectId);
        sb.append(", ").append(type);
        sb.append(", ").append(titleI18nId);
        sb.append(", ").append(author);
        sb.append(", ").append(url);
        sb.append(", ").append(thumbnail);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(videoSource);

        sb.append(")");
        return sb.toString();
    }
}
