/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class AcademicMajorPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID           id;
    private UUID           titleI18nId;
    private UUID           descriptionI18nId;
    private UUID           tagId;
    private OffsetDateTime createdOn;
    private String         createdBy;
    private OffsetDateTime updatedOn;
    private String         updatedBy;
    private String         iconPath;
    private String         serialNumber;
    private Boolean        _Deleted;

    public AcademicMajorPojo() {}

    public AcademicMajorPojo(AcademicMajorPojo value) {
        this.id = value.id;
        this.titleI18nId = value.titleI18nId;
        this.descriptionI18nId = value.descriptionI18nId;
        this.tagId = value.tagId;
        this.createdOn = value.createdOn;
        this.createdBy = value.createdBy;
        this.updatedOn = value.updatedOn;
        this.updatedBy = value.updatedBy;
        this.iconPath = value.iconPath;
        this.serialNumber = value.serialNumber;
        this._Deleted = value._Deleted;
    }

    @ConstructorProperties({ "id", "titleI18nId", "descriptionI18nId", "tagId", "createdOn", "createdBy", "updatedOn", "updatedBy", "iconPath", "serialNumber", "_Deleted" })
    public AcademicMajorPojo(
        @Nonnull UUID           id,
        @Nullable UUID           titleI18nId,
        @Nullable UUID           descriptionI18nId,
        @Nullable UUID           tagId,
        @Nullable OffsetDateTime createdOn,
        @Nullable String         createdBy,
        @Nullable OffsetDateTime updatedOn,
        @Nullable String         updatedBy,
        @Nullable String         iconPath,
        @Nullable String         serialNumber,
        @Nullable Boolean        _Deleted
    ) {
        this.id = id;
        this.titleI18nId = titleI18nId;
        this.descriptionI18nId = descriptionI18nId;
        this.tagId = tagId;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
        this.updatedOn = updatedOn;
        this.updatedBy = updatedBy;
        this.iconPath = iconPath;
        this.serialNumber = serialNumber;
        this._Deleted = _Deleted;
    }

    /**
     * Getter for <code>public.academic_major.id</code>.
     */
    @Nonnull
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.academic_major.id</code>.
     */
    public AcademicMajorPojo setId(@Nonnull UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.academic_major.title_i18n_id</code>.
     */
    @Nullable
    public UUID getTitleI18nId() {
        return this.titleI18nId;
    }

    /**
     * Setter for <code>public.academic_major.title_i18n_id</code>.
     */
    public AcademicMajorPojo setTitleI18nId(@Nullable UUID titleI18nId) {
        this.titleI18nId = titleI18nId;
        return this;
    }

    /**
     * Getter for <code>public.academic_major.description_i18n_id</code>.
     */
    @Nullable
    public UUID getDescriptionI18nId() {
        return this.descriptionI18nId;
    }

    /**
     * Setter for <code>public.academic_major.description_i18n_id</code>.
     */
    public AcademicMajorPojo setDescriptionI18nId(@Nullable UUID descriptionI18nId) {
        this.descriptionI18nId = descriptionI18nId;
        return this;
    }

    /**
     * Getter for <code>public.academic_major.tag_id</code>.
     */
    @Nullable
    public UUID getTagId() {
        return this.tagId;
    }

    /**
     * Setter for <code>public.academic_major.tag_id</code>.
     */
    public AcademicMajorPojo setTagId(@Nullable UUID tagId) {
        this.tagId = tagId;
        return this;
    }

    /**
     * Getter for <code>public.academic_major.created_on</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>public.academic_major.created_on</code>.
     */
    public AcademicMajorPojo setCreatedOn(@Nullable OffsetDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>public.academic_major.created_by</code>.
     */
    @Nullable
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.academic_major.created_by</code>.
     */
    public AcademicMajorPojo setCreatedBy(@Nullable String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.academic_major.updated_on</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>public.academic_major.updated_on</code>.
     */
    public AcademicMajorPojo setUpdatedOn(@Nullable OffsetDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    /**
     * Getter for <code>public.academic_major.updated_by</code>.
     */
    @Nullable
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>public.academic_major.updated_by</code>.
     */
    public AcademicMajorPojo setUpdatedBy(@Nullable String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Getter for <code>public.academic_major.icon_path</code>.
     */
    @Size(max = 225)
    @Nullable
    public String getIconPath() {
        return this.iconPath;
    }

    /**
     * Setter for <code>public.academic_major.icon_path</code>.
     */
    public AcademicMajorPojo setIconPath(@Nullable String iconPath) {
        this.iconPath = iconPath;
        return this;
    }

    /**
     * Getter for <code>public.academic_major.serial_number</code>.
     */
    @Size(max = 100)
    @Nullable
    public String getSerialNumber() {
        return this.serialNumber;
    }

    /**
     * Setter for <code>public.academic_major.serial_number</code>.
     */
    public AcademicMajorPojo setSerialNumber(@Nullable String serialNumber) {
        this.serialNumber = serialNumber;
        return this;
    }

    /**
     * Getter for <code>public.academic_major._deleted</code>.
     */
    @Nullable
    public Boolean get_Deleted() {
        return this._Deleted;
    }

    /**
     * Setter for <code>public.academic_major._deleted</code>.
     */
    public AcademicMajorPojo set_Deleted(@Nullable Boolean _Deleted) {
        this._Deleted = _Deleted;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AcademicMajorPojo (");

        sb.append(id);
        sb.append(", ").append(titleI18nId);
        sb.append(", ").append(descriptionI18nId);
        sb.append(", ").append(tagId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(iconPath);
        sb.append(", ").append(serialNumber);
        sb.append(", ").append(_Deleted);

        sb.append(")");
        return sb.toString();
    }
}
