/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class EcaProfileSectionPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID    id;
    private UUID    sectionI18nId;
    private Integer sort;

    public EcaProfileSectionPojo() {}

    public EcaProfileSectionPojo(EcaProfileSectionPojo value) {
        this.id = value.id;
        this.sectionI18nId = value.sectionI18nId;
        this.sort = value.sort;
    }

    @ConstructorProperties({ "id", "sectionI18nId", "sort" })
    public EcaProfileSectionPojo(
        @Nonnull UUID    id,
        @Nullable UUID    sectionI18nId,
        @Nullable Integer sort
    ) {
        this.id = id;
        this.sectionI18nId = sectionI18nId;
        this.sort = sort;
    }

    /**
     * Getter for <code>public.eca_profile_section.id</code>.
     */
    @Nonnull
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.eca_profile_section.id</code>.
     */
    public EcaProfileSectionPojo setId(@Nonnull UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.eca_profile_section.section_i18n_id</code>.
     */
    @Nullable
    public UUID getSectionI18nId() {
        return this.sectionI18nId;
    }

    /**
     * Setter for <code>public.eca_profile_section.section_i18n_id</code>.
     */
    public EcaProfileSectionPojo setSectionI18nId(@Nullable UUID sectionI18nId) {
        this.sectionI18nId = sectionI18nId;
        return this;
    }

    /**
     * Getter for <code>public.eca_profile_section.sort</code>.
     */
    @Nullable
    public Integer getSort() {
        return this.sort;
    }

    /**
     * Setter for <code>public.eca_profile_section.sort</code>.
     */
    public EcaProfileSectionPojo setSort(@Nullable Integer sort) {
        this.sort = sort;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EcaProfileSectionPojo (");

        sb.append(id);
        sb.append(", ").append(sectionI18nId);
        sb.append(", ").append(sort);

        sb.append(")");
        return sb.toString();
    }
}
