/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;

import unid.jooqMono.model.enums.EventStatusEnum;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class EventExtensionPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID            id;
    private UUID            eventId;
    private UUID            educatorProfileId;
    private String          agenda;
    private EventStatusEnum eventStatus;
    private LocalDate[]     eventDates;
    private UUID            agendaI18nId;

    public EventExtensionPojo() {}

    public EventExtensionPojo(EventExtensionPojo value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.educatorProfileId = value.educatorProfileId;
        this.agenda = value.agenda;
        this.eventStatus = value.eventStatus;
        this.eventDates = value.eventDates;
        this.agendaI18nId = value.agendaI18nId;
    }

    @ConstructorProperties({ "id", "eventId", "educatorProfileId", "agenda", "eventStatus", "eventDates", "agendaI18nId" })
    public EventExtensionPojo(
        @Nonnull UUID            id,
        @Nullable UUID            eventId,
        @Nullable UUID            educatorProfileId,
        @Nullable String          agenda,
        @Nullable EventStatusEnum eventStatus,
        @Nullable LocalDate[]     eventDates,
        @Nullable UUID            agendaI18nId
    ) {
        this.id = id;
        this.eventId = eventId;
        this.educatorProfileId = educatorProfileId;
        this.agenda = agenda;
        this.eventStatus = eventStatus;
        this.eventDates = eventDates;
        this.agendaI18nId = agendaI18nId;
    }

    /**
     * Getter for <code>public.event_extension.id</code>.
     */
    @Nonnull
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.event_extension.id</code>.
     */
    public EventExtensionPojo setId(@Nonnull UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.event_extension.event_id</code>.
     */
    @Nullable
    public UUID getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>public.event_extension.event_id</code>.
     */
    public EventExtensionPojo setEventId(@Nullable UUID eventId) {
        this.eventId = eventId;
        return this;
    }

    /**
     * Getter for <code>public.event_extension.educator_profile_id</code>.
     */
    @Nullable
    public UUID getEducatorProfileId() {
        return this.educatorProfileId;
    }

    /**
     * Setter for <code>public.event_extension.educator_profile_id</code>.
     */
    public EventExtensionPojo setEducatorProfileId(@Nullable UUID educatorProfileId) {
        this.educatorProfileId = educatorProfileId;
        return this;
    }

    /**
     * Getter for <code>public.event_extension.agenda</code>.
     */
    @Nullable
    public String getAgenda() {
        return this.agenda;
    }

    /**
     * Setter for <code>public.event_extension.agenda</code>.
     */
    public EventExtensionPojo setAgenda(@Nullable String agenda) {
        this.agenda = agenda;
        return this;
    }

    /**
     * Getter for <code>public.event_extension.event_status</code>.
     */
    @Nullable
    public EventStatusEnum getEventStatus() {
        return this.eventStatus;
    }

    /**
     * Setter for <code>public.event_extension.event_status</code>.
     */
    public EventExtensionPojo setEventStatus(@Nullable EventStatusEnum eventStatus) {
        this.eventStatus = eventStatus;
        return this;
    }

    /**
     * Getter for <code>public.event_extension.event_dates</code>.
     */
    @Nullable
    public LocalDate[] getEventDates() {
        return this.eventDates;
    }

    /**
     * Setter for <code>public.event_extension.event_dates</code>.
     */
    public EventExtensionPojo setEventDates(@Nullable LocalDate[] eventDates) {
        this.eventDates = eventDates;
        return this;
    }

    /**
     * Getter for <code>public.event_extension.agenda_i18n_id</code>.
     */
    @Nullable
    public UUID getAgendaI18nId() {
        return this.agendaI18nId;
    }

    /**
     * Setter for <code>public.event_extension.agenda_i18n_id</code>.
     */
    public EventExtensionPojo setAgendaI18nId(@Nullable UUID agendaI18nId) {
        this.agendaI18nId = agendaI18nId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EventExtensionPojo (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(educatorProfileId);
        sb.append(", ").append(agenda);
        sb.append(", ").append(eventStatus);
        sb.append(", ").append(Arrays.toString(eventDates));
        sb.append(", ").append(agendaI18nId);

        sb.append(")");
        return sb.toString();
    }
}
