/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;

import unid.jooqMono.model.enums.DeletedTypeEnum;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class SchoolExtensionPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID            id;
    private BigDecimal      rate;
    private BigDecimal      population;
    private BigDecimal      tuition;
    private String          factor;
    private DeletedTypeEnum deleted;
    private UUID            schoolId;

    public SchoolExtensionPojo() {}

    public SchoolExtensionPojo(SchoolExtensionPojo value) {
        this.id = value.id;
        this.rate = value.rate;
        this.population = value.population;
        this.tuition = value.tuition;
        this.factor = value.factor;
        this.deleted = value.deleted;
        this.schoolId = value.schoolId;
    }

    @ConstructorProperties({ "id", "rate", "population", "tuition", "factor", "deleted", "schoolId" })
    public SchoolExtensionPojo(
        @Nonnull UUID            id,
        @Nullable BigDecimal      rate,
        @Nullable BigDecimal      population,
        @Nullable BigDecimal      tuition,
        @Nullable String          factor,
        @Nullable DeletedTypeEnum deleted,
        @Nullable UUID            schoolId
    ) {
        this.id = id;
        this.rate = rate;
        this.population = population;
        this.tuition = tuition;
        this.factor = factor;
        this.deleted = deleted;
        this.schoolId = schoolId;
    }

    /**
     * Getter for <code>public.school_extension.id</code>.
     */
    @Nonnull
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.school_extension.id</code>.
     */
    public SchoolExtensionPojo setId(@Nonnull UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.school_extension.rate</code>.
     */
    @Nullable
    public BigDecimal getRate() {
        return this.rate;
    }

    /**
     * Setter for <code>public.school_extension.rate</code>.
     */
    public SchoolExtensionPojo setRate(@Nullable BigDecimal rate) {
        this.rate = rate;
        return this;
    }

    /**
     * Getter for <code>public.school_extension.population</code>.
     */
    @Nullable
    public BigDecimal getPopulation() {
        return this.population;
    }

    /**
     * Setter for <code>public.school_extension.population</code>.
     */
    public SchoolExtensionPojo setPopulation(@Nullable BigDecimal population) {
        this.population = population;
        return this;
    }

    /**
     * Getter for <code>public.school_extension.tuition</code>.
     */
    @Nullable
    public BigDecimal getTuition() {
        return this.tuition;
    }

    /**
     * Setter for <code>public.school_extension.tuition</code>.
     */
    public SchoolExtensionPojo setTuition(@Nullable BigDecimal tuition) {
        this.tuition = tuition;
        return this;
    }

    /**
     * Getter for <code>public.school_extension.factor</code>.
     */
    @Nullable
    public String getFactor() {
        return this.factor;
    }

    /**
     * Setter for <code>public.school_extension.factor</code>.
     */
    public SchoolExtensionPojo setFactor(@Nullable String factor) {
        this.factor = factor;
        return this;
    }

    /**
     * Getter for <code>public.school_extension.deleted</code>.
     */
    @Nullable
    public DeletedTypeEnum getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>public.school_extension.deleted</code>.
     */
    public SchoolExtensionPojo setDeleted(@Nullable DeletedTypeEnum deleted) {
        this.deleted = deleted;
        return this;
    }

    /**
     * Getter for <code>public.school_extension.school_id</code>.
     */
    @Nullable
    public UUID getSchoolId() {
        return this.schoolId;
    }

    /**
     * Setter for <code>public.school_extension.school_id</code>.
     */
    public SchoolExtensionPojo setSchoolId(@Nullable UUID schoolId) {
        this.schoolId = schoolId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SchoolExtensionPojo (");

        sb.append(id);
        sb.append(", ").append(rate);
        sb.append(", ").append(population);
        sb.append(", ").append(tuition);
        sb.append(", ").append(factor);
        sb.append(", ").append(deleted);
        sb.append(", ").append(schoolId);

        sb.append(")");
        return sb.toString();
    }
}
