/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@lombok.experimental.FieldNameConstants(innerTypeName = "Columns")
public class StudentProfilePredictedGradePojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID           id;
    private UUID           studentProfileId;
    private UUID           academicSubjectId;
    private String         grade;
    private OffsetDateTime createdOn;
    private String         createdBy;
    private OffsetDateTime updatedOn;
    private String         updatedBy;

    public StudentProfilePredictedGradePojo() {}

    public StudentProfilePredictedGradePojo(StudentProfilePredictedGradePojo value) {
        this.id = value.id;
        this.studentProfileId = value.studentProfileId;
        this.academicSubjectId = value.academicSubjectId;
        this.grade = value.grade;
        this.createdOn = value.createdOn;
        this.createdBy = value.createdBy;
        this.updatedOn = value.updatedOn;
        this.updatedBy = value.updatedBy;
    }

    @ConstructorProperties({ "id", "studentProfileId", "academicSubjectId", "grade", "createdOn", "createdBy", "updatedOn", "updatedBy" })
    public StudentProfilePredictedGradePojo(
        @Nonnull UUID           id,
        @Nonnull UUID           studentProfileId,
        @Nonnull UUID           academicSubjectId,
        @Nonnull String         grade,
        @Nullable OffsetDateTime createdOn,
        @Nullable String         createdBy,
        @Nullable OffsetDateTime updatedOn,
        @Nullable String         updatedBy
    ) {
        this.id = id;
        this.studentProfileId = studentProfileId;
        this.academicSubjectId = academicSubjectId;
        this.grade = grade;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
        this.updatedOn = updatedOn;
        this.updatedBy = updatedBy;
    }

    /**
     * Getter for <code>public.student_profile_predicted_grade.id</code>.
     */
    @Nonnull
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.student_profile_predicted_grade.id</code>.
     */
    public StudentProfilePredictedGradePojo setId(@Nonnull UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for
     * <code>public.student_profile_predicted_grade.student_profile_id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getStudentProfileId() {
        return this.studentProfileId;
    }

    /**
     * Setter for
     * <code>public.student_profile_predicted_grade.student_profile_id</code>.
     */
    public StudentProfilePredictedGradePojo setStudentProfileId(@Nonnull UUID studentProfileId) {
        this.studentProfileId = studentProfileId;
        return this;
    }

    /**
     * Getter for
     * <code>public.student_profile_predicted_grade.academic_subject_id</code>.
     */
    @NotNull
    @Nonnull
    public UUID getAcademicSubjectId() {
        return this.academicSubjectId;
    }

    /**
     * Setter for
     * <code>public.student_profile_predicted_grade.academic_subject_id</code>.
     */
    public StudentProfilePredictedGradePojo setAcademicSubjectId(@Nonnull UUID academicSubjectId) {
        this.academicSubjectId = academicSubjectId;
        return this;
    }

    /**
     * Getter for <code>public.student_profile_predicted_grade.grade</code>.
     */
    @NotNull
    @Nonnull
    public String getGrade() {
        return this.grade;
    }

    /**
     * Setter for <code>public.student_profile_predicted_grade.grade</code>.
     */
    public StudentProfilePredictedGradePojo setGrade(@Nonnull String grade) {
        this.grade = grade;
        return this;
    }

    /**
     * Getter for
     * <code>public.student_profile_predicted_grade.created_on</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for
     * <code>public.student_profile_predicted_grade.created_on</code>.
     */
    public StudentProfilePredictedGradePojo setCreatedOn(@Nullable OffsetDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for
     * <code>public.student_profile_predicted_grade.created_by</code>.
     */
    @Nullable
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for
     * <code>public.student_profile_predicted_grade.created_by</code>.
     */
    public StudentProfilePredictedGradePojo setCreatedBy(@Nullable String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for
     * <code>public.student_profile_predicted_grade.updated_on</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for
     * <code>public.student_profile_predicted_grade.updated_on</code>.
     */
    public StudentProfilePredictedGradePojo setUpdatedOn(@Nullable OffsetDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    /**
     * Getter for
     * <code>public.student_profile_predicted_grade.updated_by</code>.
     */
    @Nullable
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for
     * <code>public.student_profile_predicted_grade.updated_by</code>.
     */
    public StudentProfilePredictedGradePojo setUpdatedBy(@Nullable String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StudentProfilePredictedGradePojo (");

        sb.append(id);
        sb.append(", ").append(studentProfileId);
        sb.append(", ").append(academicSubjectId);
        sb.append(", ").append(grade);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }
}
