/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables;


import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row20;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import unid.jooqMono.model.Public;
import unid.jooqMono.model.tables.records._AuditLogStudentUploadedWritingRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _AuditLogStudentUploadedWritingTable extends TableImpl<_AuditLogStudentUploadedWritingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public._audit_log_student_uploaded_writing</code>
     */
    public static final _AuditLogStudentUploadedWritingTable _AUDIT_LOG_STUDENT_UPLOADED_WRITING = new _AuditLogStudentUploadedWritingTable();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<_AuditLogStudentUploadedWritingRecord> getRecordType() {
        return _AuditLogStudentUploadedWritingRecord.class;
    }

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.audit_seq</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, Long> AUDIT_SEQ = createField(DSL.name("audit_seq"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.audit_createdon</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, OffsetDateTime> AUDIT_CREATEDON = createField(DSL.name("audit_createdon"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.audit_createdby</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, String> AUDIT_CREATEDBY = createField(DSL.name("audit_createdby"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.audit_operation</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, String> AUDIT_OPERATION = createField(DSL.name("audit_operation"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.audit_type</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, String> AUDIT_TYPE = createField(DSL.name("audit_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public._audit_log_student_uploaded_writing.id</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.student_profile_id</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, UUID> STUDENT_PROFILE_ID = createField(DSL.name("student_profile_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.writing_topic_id</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, UUID> WRITING_TOPIC_ID = createField(DSL.name("writing_topic_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.payment_transaction_id</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, UUID> PAYMENT_TRANSACTION_ID = createField(DSL.name("payment_transaction_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.uploaded_file</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, String> UPLOADED_FILE = createField(DSL.name("uploaded_file"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.grammar_and_expression_review_id</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, UUID> GRAMMAR_AND_EXPRESSION_REVIEW_ID = createField(DSL.name("grammar_and_expression_review_id"), SQLDataType.UUID, this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.content_review_id</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, UUID> CONTENT_REVIEW_ID = createField(DSL.name("content_review_id"), SQLDataType.UUID, this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.composition_review_id</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, UUID> COMPOSITION_REVIEW_ID = createField(DSL.name("composition_review_id"), SQLDataType.UUID, this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.created_on</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, OffsetDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.created_by</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.updated_on</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, OffsetDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.updated_by</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.recommended_activity</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, String[]> RECOMMENDED_ACTIVITY = createField(DSL.name("recommended_activity"), SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.recommendation</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, String> RECOMMENDATION = createField(DSL.name("recommendation"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public._audit_log_student_uploaded_writing.serial_number</code>.
     */
    public final TableField<_AuditLogStudentUploadedWritingRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(255), this, "");

    private _AuditLogStudentUploadedWritingTable(Name alias, Table<_AuditLogStudentUploadedWritingRecord> aliased) {
        this(alias, aliased, null);
    }

    private _AuditLogStudentUploadedWritingTable(Name alias, Table<_AuditLogStudentUploadedWritingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public._audit_log_student_uploaded_writing</code>
     * table reference
     */
    public _AuditLogStudentUploadedWritingTable(String alias) {
        this(DSL.name(alias), _AUDIT_LOG_STUDENT_UPLOADED_WRITING);
    }

    /**
     * Create an aliased <code>public._audit_log_student_uploaded_writing</code>
     * table reference
     */
    public _AuditLogStudentUploadedWritingTable(Name alias) {
        this(alias, _AUDIT_LOG_STUDENT_UPLOADED_WRITING);
    }

    /**
     * Create a <code>public._audit_log_student_uploaded_writing</code> table
     * reference
     */
    public _AuditLogStudentUploadedWritingTable() {
        this(DSL.name("_audit_log_student_uploaded_writing"), null);
    }

    public <O extends Record> _AuditLogStudentUploadedWritingTable(Table<O> child, ForeignKey<O, _AuditLogStudentUploadedWritingRecord> key) {
        super(child, key, _AUDIT_LOG_STUDENT_UPLOADED_WRITING);
    }

    @Override
    @Nonnull
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public Identity<_AuditLogStudentUploadedWritingRecord, Long> getIdentity() {
        return (Identity<_AuditLogStudentUploadedWritingRecord, Long>) super.getIdentity();
    }

    @Override
    @Nonnull
    public _AuditLogStudentUploadedWritingTable as(String alias) {
        return new _AuditLogStudentUploadedWritingTable(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public _AuditLogStudentUploadedWritingTable as(Name alias) {
        return new _AuditLogStudentUploadedWritingTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public _AuditLogStudentUploadedWritingTable rename(String name) {
        return new _AuditLogStudentUploadedWritingTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public _AuditLogStudentUploadedWritingTable rename(Name name) {
        return new _AuditLogStudentUploadedWritingTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row20 type methods
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row20<Long, OffsetDateTime, String, String, String, UUID, UUID, UUID, UUID, String, UUID, UUID, UUID, OffsetDateTime, String, OffsetDateTime, String, String[], String, String> fieldsRow() {
        return (Row20) super.fieldsRow();
    }
}
