/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables;


import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import unid.jooqMono.model.Public;
import unid.jooqMono.model.tables.records._AuditLogEducatorSessionNoteMapRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _AuditLogEducatorSessionNoteMapTable extends TableImpl<_AuditLogEducatorSessionNoteMapRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public._audit_log_educator_session_note_map</code>
     */
    public static final _AuditLogEducatorSessionNoteMapTable _AUDIT_LOG_EDUCATOR_SESSION_NOTE_MAP = new _AuditLogEducatorSessionNoteMapTable();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<_AuditLogEducatorSessionNoteMapRecord> getRecordType() {
        return _AuditLogEducatorSessionNoteMapRecord.class;
    }

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.audit_seq</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, Long> AUDIT_SEQ = createField(DSL.name("audit_seq"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.audit_createdon</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, OffsetDateTime> AUDIT_CREATEDON = createField(DSL.name("audit_createdon"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.audit_createdby</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, String> AUDIT_CREATEDBY = createField(DSL.name("audit_createdby"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.audit_operation</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, String> AUDIT_OPERATION = createField(DSL.name("audit_operation"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.audit_type</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, String> AUDIT_TYPE = createField(DSL.name("audit_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public._audit_log_educator_session_note_map.id</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.educator_calendar_id</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, UUID> EDUCATOR_CALENDAR_ID = createField(DSL.name("educator_calendar_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.educator_session_note_item_id</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, UUID> EDUCATOR_SESSION_NOTE_ITEM_ID = createField(DSL.name("educator_session_note_item_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.note_item_input</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, String> NOTE_ITEM_INPUT = createField(DSL.name("note_item_input"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.created_on</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, OffsetDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.created_by</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.updated_on</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, OffsetDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column
     * <code>public._audit_log_educator_session_note_map.updated_by</code>.
     */
    public final TableField<_AuditLogEducatorSessionNoteMapRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.CLOB, this, "");

    private _AuditLogEducatorSessionNoteMapTable(Name alias, Table<_AuditLogEducatorSessionNoteMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private _AuditLogEducatorSessionNoteMapTable(Name alias, Table<_AuditLogEducatorSessionNoteMapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased
     * <code>public._audit_log_educator_session_note_map</code> table reference
     */
    public _AuditLogEducatorSessionNoteMapTable(String alias) {
        this(DSL.name(alias), _AUDIT_LOG_EDUCATOR_SESSION_NOTE_MAP);
    }

    /**
     * Create an aliased
     * <code>public._audit_log_educator_session_note_map</code> table reference
     */
    public _AuditLogEducatorSessionNoteMapTable(Name alias) {
        this(alias, _AUDIT_LOG_EDUCATOR_SESSION_NOTE_MAP);
    }

    /**
     * Create a <code>public._audit_log_educator_session_note_map</code> table
     * reference
     */
    public _AuditLogEducatorSessionNoteMapTable() {
        this(DSL.name("_audit_log_educator_session_note_map"), null);
    }

    public <O extends Record> _AuditLogEducatorSessionNoteMapTable(Table<O> child, ForeignKey<O, _AuditLogEducatorSessionNoteMapRecord> key) {
        super(child, key, _AUDIT_LOG_EDUCATOR_SESSION_NOTE_MAP);
    }

    @Override
    @Nonnull
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public Identity<_AuditLogEducatorSessionNoteMapRecord, Long> getIdentity() {
        return (Identity<_AuditLogEducatorSessionNoteMapRecord, Long>) super.getIdentity();
    }

    @Override
    @Nonnull
    public _AuditLogEducatorSessionNoteMapTable as(String alias) {
        return new _AuditLogEducatorSessionNoteMapTable(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public _AuditLogEducatorSessionNoteMapTable as(Name alias) {
        return new _AuditLogEducatorSessionNoteMapTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public _AuditLogEducatorSessionNoteMapTable rename(String name) {
        return new _AuditLogEducatorSessionNoteMapTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public _AuditLogEducatorSessionNoteMapTable rename(Name name) {
        return new _AuditLogEducatorSessionNoteMapTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row13<Long, OffsetDateTime, String, String, String, UUID, UUID, UUID, String, OffsetDateTime, String, OffsetDateTime, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
