/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import unid.jooqMono.model.Keys;
import unid.jooqMono.model.Public;
import unid.jooqMono.model.enums.AcademicSubjectResourceTypeEnum;
import unid.jooqMono.model.tables.records.AcademicSubjectResourceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AcademicSubjectResourceTable extends TableImpl<AcademicSubjectResourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.academic_subject_resource</code>
     */
    public static final AcademicSubjectResourceTable ACADEMIC_SUBJECT_RESOURCE = new AcademicSubjectResourceTable();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<AcademicSubjectResourceRecord> getRecordType() {
        return AcademicSubjectResourceRecord.class;
    }

    /**
     * The column <code>public.academic_subject_resource.id</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("gen_random_uuid()", SQLDataType.UUID)), this, "");

    /**
     * The column
     * <code>public.academic_subject_resource.academic_subject_id</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, UUID> ACADEMIC_SUBJECT_ID = createField(DSL.name("academic_subject_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.academic_subject_resource.type</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, AcademicSubjectResourceTypeEnum> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR.asEnumDataType(unid.jooqMono.model.enums.AcademicSubjectResourceTypeEnum.class), this, "");

    /**
     * The column <code>public.academic_subject_resource.title_i18n_id</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, UUID> TITLE_I18N_ID = createField(DSL.name("title_i18n_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.academic_subject_resource.author</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, String> AUTHOR = createField(DSL.name("author"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.academic_subject_resource.url</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, String> URL = createField(DSL.name("url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.academic_subject_resource.thumbnail</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, String> THUMBNAIL = createField(DSL.name("thumbnail"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.academic_subject_resource.created_on</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, OffsetDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.academic_subject_resource.created_by</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.academic_subject_resource.updated_on</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, OffsetDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.academic_subject_resource.updated_by</code>.
     */
    public final TableField<AcademicSubjectResourceRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.CLOB, this, "");

    private AcademicSubjectResourceTable(Name alias, Table<AcademicSubjectResourceRecord> aliased) {
        this(alias, aliased, null);
    }

    private AcademicSubjectResourceTable(Name alias, Table<AcademicSubjectResourceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.academic_subject_resource</code> table
     * reference
     */
    public AcademicSubjectResourceTable(String alias) {
        this(DSL.name(alias), ACADEMIC_SUBJECT_RESOURCE);
    }

    /**
     * Create an aliased <code>public.academic_subject_resource</code> table
     * reference
     */
    public AcademicSubjectResourceTable(Name alias) {
        this(alias, ACADEMIC_SUBJECT_RESOURCE);
    }

    /**
     * Create a <code>public.academic_subject_resource</code> table reference
     */
    public AcademicSubjectResourceTable() {
        this(DSL.name("academic_subject_resource"), null);
    }

    public <O extends Record> AcademicSubjectResourceTable(Table<O> child, ForeignKey<O, AcademicSubjectResourceRecord> key) {
        super(child, key, ACADEMIC_SUBJECT_RESOURCE);
    }

    @Override
    @Nonnull
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public UniqueKey<AcademicSubjectResourceRecord> getPrimaryKey() {
        return Keys.ACADEMIC_SUBJECT_RESOURCE_PKEY;
    }

    @Override
    @Nonnull
    public List<UniqueKey<AcademicSubjectResourceRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ACADEMIC_SUBJECT_RESOURCE_TITLE_I18N_ID_KEY);
    }

    @Override
    @Nonnull
    public List<ForeignKey<AcademicSubjectResourceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ACADEMIC_SUBJECT_RESOURCE__FK_ACAD_SUB_RESC_ACAD_SUB, Keys.ACADEMIC_SUBJECT_RESOURCE__FK_ACAD_SUB_RESC_TITL);
    }

    private transient AcademicSubjectTable _academicSubject;
    private transient I18nTable _i18n;

    public AcademicSubjectTable academicSubject() {
        if (_academicSubject == null)
            _academicSubject = new AcademicSubjectTable(this, Keys.ACADEMIC_SUBJECT_RESOURCE__FK_ACAD_SUB_RESC_ACAD_SUB);

        return _academicSubject;
    }

    public I18nTable i18n() {
        if (_i18n == null)
            _i18n = new I18nTable(this, Keys.ACADEMIC_SUBJECT_RESOURCE__FK_ACAD_SUB_RESC_TITL);

        return _i18n;
    }

    @Override
    @Nonnull
    public AcademicSubjectResourceTable as(String alias) {
        return new AcademicSubjectResourceTable(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public AcademicSubjectResourceTable as(Name alias) {
        return new AcademicSubjectResourceTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public AcademicSubjectResourceTable rename(String name) {
        return new AcademicSubjectResourceTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public AcademicSubjectResourceTable rename(Name name) {
        return new AcademicSubjectResourceTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row11<UUID, UUID, AcademicSubjectResourceTypeEnum, UUID, String, String, String, OffsetDateTime, String, OffsetDateTime, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
