DO
$$
    BEGIN

        CREATE TYPE "user_notification_type" AS ENUM (
            'EDUCATOR_BOOKING_REQUEST',
            'EDUCATOR_BOOKING_RESPONSE',
            'STUDENT_MEETING_ENDED_FEEDBACK_REQUEST',
            'STUDENT_MEETING_ENDED_FEEDBACK_RESPONSE',
            'EDUCATOR_MEETING_ENDED_FEEDBACK_REQUEST',
            'EDUCATOR_MEETING_ENDED_FEEDBACK_RESPONSE',
            'STUDENT_WRITING_COMMENT_RESPONSE',
            'STUDENT_INTERVIEW_COMMENT_RESPONSE'
            );

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;

            RAISE;

    END;

$$;