/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.daos;


import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import unid.jooqMono.model.tables.EcaCourseAcademicMajorEducationLevelMapTable;
import unid.jooqMono.model.tables.pojos.EcaCourseAcademicMajorEducationLevelMapPojo;
import unid.jooqMono.model.tables.records.EcaCourseAcademicMajorEducationLevelMapRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EcaCourseAcademicMajorEducationLevelMapDao extends DAOImpl<EcaCourseAcademicMajorEducationLevelMapRecord, EcaCourseAcademicMajorEducationLevelMapPojo, UUID> {

    /**
     * Create a new EcaCourseAcademicMajorEducationLevelMapDao without any
     * configuration
     */
    public EcaCourseAcademicMajorEducationLevelMapDao() {
        super(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP, EcaCourseAcademicMajorEducationLevelMapPojo.class);
    }

    /**
     * Create a new EcaCourseAcademicMajorEducationLevelMapDao with an attached
     * configuration
     */
    public EcaCourseAcademicMajorEducationLevelMapDao(Configuration configuration) {
        super(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP, EcaCourseAcademicMajorEducationLevelMapPojo.class, configuration);
    }

    @Override
    @Nonnull
    public UUID getId(EcaCourseAcademicMajorEducationLevelMapPojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchById(UUID... values) {
        return fetch(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    @Nullable
    public EcaCourseAcademicMajorEducationLevelMapPojo fetchOneById(UUID value) {
        return fetchOne(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.ID, value);
    }

    /**
     * Fetch records that have <code>eca_course_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchRangeOfEcaCourseId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.ECA_COURSE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>eca_course_id IN (values)</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchByEcaCourseId(UUID... values) {
        return fetch(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.ECA_COURSE_ID, values);
    }

    /**
     * Fetch records that have <code>education_level_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchRangeOfEducationLevelId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.EDUCATION_LEVEL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>education_level_id IN (values)</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchByEducationLevelId(UUID... values) {
        return fetch(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.EDUCATION_LEVEL_ID, values);
    }

    /**
     * Fetch records that have <code>created_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchRangeOfCreatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchByCreatedOn(OffsetDateTime... values) {
        return fetch(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchRangeOfCreatedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchByCreatedBy(String... values) {
        return fetch(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>updated_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchRangeOfUpdatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.UPDATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_on IN (values)</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchByUpdatedOn(OffsetDateTime... values) {
        return fetch(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.UPDATED_ON, values);
    }

    /**
     * Fetch records that have <code>updated_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchRangeOfUpdatedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.UPDATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_by IN (values)</code>
     */
    @Nonnull
    public List<EcaCourseAcademicMajorEducationLevelMapPojo> fetchByUpdatedBy(String... values) {
        return fetch(EcaCourseAcademicMajorEducationLevelMapTable.ECA_COURSE_ACADEMIC_MAJOR_EDUCATION_LEVEL_MAP.UPDATED_BY, values);
    }
}
