/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.daos;


import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import unid.jooqMono.model.tables.EducatorProfileLanguageMapTable;
import unid.jooqMono.model.tables.pojos.EducatorProfileLanguageMapPojo;
import unid.jooqMono.model.tables.records.EducatorProfileLanguageMapRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EducatorProfileLanguageMapDao extends DAOImpl<EducatorProfileLanguageMapRecord, EducatorProfileLanguageMapPojo, UUID> {

    /**
     * Create a new EducatorProfileLanguageMapDao without any configuration
     */
    public EducatorProfileLanguageMapDao() {
        super(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP, EducatorProfileLanguageMapPojo.class);
    }

    /**
     * Create a new EducatorProfileLanguageMapDao with an attached configuration
     */
    public EducatorProfileLanguageMapDao(Configuration configuration) {
        super(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP, EducatorProfileLanguageMapPojo.class, configuration);
    }

    @Override
    @Nonnull
    public UUID getId(EducatorProfileLanguageMapPojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchById(UUID... values) {
        return fetch(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    @Nullable
    public EducatorProfileLanguageMapPojo fetchOneById(UUID value) {
        return fetchOne(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.ID, value);
    }

    /**
     * Fetch records that have <code>educator_profile_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchRangeOfEducatorProfileId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.EDUCATOR_PROFILE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>educator_profile_id IN (values)</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchByEducatorProfileId(UUID... values) {
        return fetch(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.EDUCATOR_PROFILE_ID, values);
    }

    /**
     * Fetch records that have <code>language_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchRangeOfLanguageId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.LANGUAGE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>language_id IN (values)</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchByLanguageId(UUID... values) {
        return fetch(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.LANGUAGE_ID, values);
    }

    /**
     * Fetch records that have <code>created_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchRangeOfCreatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchByCreatedOn(OffsetDateTime... values) {
        return fetch(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchRangeOfCreatedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchByCreatedBy(String... values) {
        return fetch(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>updated_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchRangeOfUpdatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.UPDATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_on IN (values)</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchByUpdatedOn(OffsetDateTime... values) {
        return fetch(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.UPDATED_ON, values);
    }

    /**
     * Fetch records that have <code>updated_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchRangeOfUpdatedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.UPDATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_by IN (values)</code>
     */
    @Nonnull
    public List<EducatorProfileLanguageMapPojo> fetchByUpdatedBy(String... values) {
        return fetch(EducatorProfileLanguageMapTable.EDUCATOR_PROFILE_LANGUAGE_MAP.UPDATED_BY, values);
    }
}
