/*
 * This file is generated by jOOQ.
 */
package unid.jooqMono.model.tables.daos;


import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import unid.jooqMono.model.tables.StudentSessionSurveyQuestionTable;
import unid.jooqMono.model.tables.pojos.StudentSessionSurveyQuestionPojo;
import unid.jooqMono.model.tables.records.StudentSessionSurveyQuestionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentSessionSurveyQuestionDao extends DAOImpl<StudentSessionSurveyQuestionRecord, StudentSessionSurveyQuestionPojo, UUID> {

    /**
     * Create a new StudentSessionSurveyQuestionDao without any configuration
     */
    public StudentSessionSurveyQuestionDao() {
        super(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION, StudentSessionSurveyQuestionPojo.class);
    }

    /**
     * Create a new StudentSessionSurveyQuestionDao with an attached
     * configuration
     */
    public StudentSessionSurveyQuestionDao(Configuration configuration) {
        super(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION, StudentSessionSurveyQuestionPojo.class, configuration);
    }

    @Override
    @Nonnull
    public UUID getId(StudentSessionSurveyQuestionPojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchById(UUID... values) {
        return fetch(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    @Nullable
    public StudentSessionSurveyQuestionPojo fetchOneById(UUID value) {
        return fetchOne(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.ID, value);
    }

    /**
     * Fetch records that have <code>student_session_survey_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchRangeOfStudentSessionSurveyId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.STUDENT_SESSION_SURVEY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>student_session_survey_id IN
     * (values)</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchByStudentSessionSurveyId(UUID... values) {
        return fetch(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.STUDENT_SESSION_SURVEY_ID, values);
    }

    /**
     * Fetch records that have <code>student_session_survey_version BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchRangeOfStudentSessionSurveyVersion(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.STUDENT_SESSION_SURVEY_VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>student_session_survey_version IN
     * (values)</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchByStudentSessionSurveyVersion(OffsetDateTime... values) {
        return fetch(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.STUDENT_SESSION_SURVEY_VERSION, values);
    }

    /**
     * Fetch records that have <code>order BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchRangeOfOrder(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.ORDER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>order IN (values)</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchByOrder(Integer... values) {
        return fetch(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.ORDER, values);
    }

    /**
     * Fetch records that have <code>description_i18n_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchRangeOfDescriptionI18nId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.DESCRIPTION_I18N_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description_i18n_id IN (values)</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchByDescriptionI18nId(UUID... values) {
        return fetch(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.DESCRIPTION_I18N_ID, values);
    }

    /**
     * Fetch a unique record that has <code>description_i18n_id = value</code>
     */
    @Nullable
    public StudentSessionSurveyQuestionPojo fetchOneByDescriptionI18nId(UUID value) {
        return fetchOne(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.DESCRIPTION_I18N_ID, value);
    }

    /**
     * Fetch records that have <code>mandatory BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchRangeOfMandatory(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.MANDATORY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mandatory IN (values)</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchByMandatory(Boolean... values) {
        return fetch(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.MANDATORY, values);
    }

    /**
     * Fetch records that have <code>created_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchRangeOfCreatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchByCreatedOn(OffsetDateTime... values) {
        return fetch(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchRangeOfCreatedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchByCreatedBy(String... values) {
        return fetch(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>updated_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchRangeOfUpdatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.UPDATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_on IN (values)</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchByUpdatedOn(OffsetDateTime... values) {
        return fetch(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.UPDATED_ON, values);
    }

    /**
     * Fetch records that have <code>updated_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchRangeOfUpdatedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.UPDATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_by IN (values)</code>
     */
    @Nonnull
    public List<StudentSessionSurveyQuestionPojo> fetchByUpdatedBy(String... values) {
        return fetch(StudentSessionSurveyQuestionTable.STUDENT_SESSION_SURVEY_QUESTION.UPDATED_BY, values);
    }
}
